"""Native macOS Time Machine destinations backed by Samba ``vfs_fruit``.

Ordinary Echo SMB shares use Samba's constrained usershare interface.  That
interface cannot express the Apple extensions required by Time Machine, so
this module owns one deterministic include file instead.  The include applies
``fruit`` consistently to every Samba share (required for reliable AAPL
negotiation) and contains only dedicated, authenticated backup destinations.
"""

from __future__ import annotations

import json
import re
import shutil
import stat
import subprocess
from pathlib import Path
from typing import Any

from appliance.omv_protocol import (
    TIME_MACHINE_DESIRED_SCHEMA,
    TIME_MACHINE_PLAN_SCHEMA,
    validate_time_machine_desired,
)

TIME_MACHINE_CAPABILITY = "smb.time-machine.desired.v1"
MANAGED_CONFIG = Path("/etc/samba/echo-os-time-machine.conf")
SAMBA_CONFIG = Path("/etc/samba/smb.conf")
_HEADER = "# Generated by Echo OS. Manual edits are rejected and never merged."
_INCLUDE_LINE = f"include = {MANAGED_CONFIG}"
_METADATA_PREFIX = "# echo-os-time-machine "
_VFS_MODULES = ("catia", "fruit", "streams_xattr")


def _storage() -> Any:
    # Local import avoids making native_storage's broad probe surface a module
    # import dependency for request-model validation and OpenAPI generation.
    from appliance import native_storage

    return native_storage


def _read_regular_text(path: Path, *, missing_ok: bool = False) -> str | None:
    try:
        info = path.lstat()
    except FileNotFoundError:
        if missing_ok:
            return None
        raise
    if not stat.S_ISREG(info.st_mode) or stat.S_ISLNK(info.st_mode):
        raise OSError(f"managed Samba file is not a regular file: {path}")
    try:
        return path.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as exc:
        raise OSError(f"managed Samba file is unreadable: {path}") from exc


def _safe_config_path(value: Path) -> str:
    text = str(value)
    if not value.is_absolute() or any(ord(character) < 32 for character in text):
        raise OSError("Time Machine path cannot be represented safely in Samba configuration")
    return text


def _entry_for_desired(desired: dict[str, Any]) -> dict[str, Any]:
    storage = _storage()
    folder = storage._resolve_shared_folder(desired["sharedFolderRef"])
    path = storage._native_registered_path(folder)
    name = storage._registered_relative_name(folder, strict=True)
    assert name is not None
    return {
        "sharedFolderRef": desired["sharedFolderRef"],
        "name": name,
        "path": _safe_config_path(path),
        "owner": desired["owner"],
        "maximumBytes": desired["maximumBytes"],
    }


def _validate_entry(value: Any) -> dict[str, Any]:
    if not isinstance(value, dict) or set(value) != {
        "sharedFolderRef",
        "name",
        "path",
        "owner",
        "maximumBytes",
    }:
        raise OSError("Echo-managed Time Machine configuration has invalid metadata")
    desired = validate_time_machine_desired(
        {
            "schema": TIME_MACHINE_DESIRED_SCHEMA,
            "sharedFolderRef": value.get("sharedFolderRef"),
            "enabled": True,
            "owner": value.get("owner"),
            "maximumBytes": value.get("maximumBytes"),
        }
    )
    expected = _entry_for_desired(desired)
    if value != expected:
        raise OSError("Echo-managed Time Machine configuration has stale or unsafe metadata")
    return expected


def render_config(entries: list[dict[str, Any]]) -> str:
    """Render the complete include deterministically from canonical metadata."""
    normalized = sorted((_validate_entry(entry) for entry in entries), key=lambda row: row["name"])
    names = [entry["name"].casefold() for entry in normalized]
    folders = [entry["sharedFolderRef"] for entry in normalized]
    if len(names) != len(set(names)) or len(folders) != len(set(folders)):
        raise OSError("Echo-managed Time Machine configuration contains duplicate shares")

    lines = [
        _HEADER,
        "# Included from the [global] section of /etc/samba/smb.conf.",
        "vfs objects = catia fruit streams_xattr",
        "fruit:aapl = yes",
        "fruit:model = MacSamba",
        "fruit:nfs_aces = no",
    ]
    for entry in normalized:
        metadata = json.dumps(entry, ensure_ascii=True, sort_keys=True, separators=(",", ":"))
        gib = entry["maximumBytes"] // 1024**3
        lines.extend(
            [
                "",
                f"{_METADATA_PREFIX}{metadata}",
                f"[{entry['name']}]",
                f"path = {entry['path']}",
                "browseable = yes",
                "read only = no",
                "guest ok = no",
                f"valid users = {entry['owner']}",
                "vfs objects = catia fruit streams_xattr",
                "fruit:time machine = yes",
                f"fruit:time machine max size = {gib}G",
                "fruit:metadata = stream",
                "fruit:resource = file",
                "fruit:encoding = native",
            ]
        )
    return "\n".join(lines) + "\n"


def _load_entries(*, strict: bool = False) -> list[dict[str, Any]]:
    try:
        text = _read_regular_text(MANAGED_CONFIG, missing_ok=True)
        if text is None:
            return []
        raw_entries = [
            json.loads(line[len(_METADATA_PREFIX) :])
            for line in text.splitlines()
            if line.startswith(_METADATA_PREFIX)
        ]
        entries = [_validate_entry(entry) for entry in raw_entries]
        if text != render_config(entries):
            raise OSError("Echo-managed Time Machine configuration was modified outside Echo OS")
        return sorted(entries, key=lambda row: row["name"])
    except (OSError, ValueError, TypeError, json.JSONDecodeError) as exc:
        if strict:
            if isinstance(exc, OSError):
                raise
            raise OSError("Echo-managed Time Machine configuration is unreadable") from exc
        return []


def _config_has_managed_include() -> bool:
    try:
        text = _read_regular_text(SAMBA_CONFIG)
    except OSError:
        return False
    assert text is not None
    section = ""
    matches = 0
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith(("#", ";")):
            continue
        if line.startswith("[") and line.endswith("]"):
            section = line[1:-1].strip().casefold()
            continue
        key, separator, raw_value = line.partition("=")
        if separator and key.strip().casefold() == "include":
            if raw_value.strip() == str(MANAGED_CONFIG) and section == "global":
                matches += 1
            elif raw_value.strip() == str(MANAGED_CONFIG):
                return False
    return matches == 1


def _run_checked(*args: str, timeout: float = 30.0) -> str:
    try:
        completed = subprocess.run(
            list(args), capture_output=True, text=True, timeout=timeout, check=False
        )
    except (OSError, subprocess.SubprocessError) as exc:
        raise OSError(f"Time Machine command failed to start: {' '.join(args)}") from exc
    if completed.returncode != 0:
        detail = (completed.stderr or completed.stdout).strip() or f"exit {completed.returncode}"
        raise OSError(f"{args[0]} failed: {detail}")
    return completed.stdout or ""


def _samba_modules_available() -> bool:
    try:
        output = _run_checked("smbd", "-b", timeout=10.0)
        match = re.search(r"(?m)^\s*MODULESDIR:\s*(\S.*?)\s*$", output)
        if match is None:
            return False
        module_root = Path(match.group(1)) / "vfs"
        return all((module_root / f"{name}.so").is_file() for name in _VFS_MODULES)
    except OSError:
        return False


def capability_available() -> bool:
    try:
        if any(shutil.which(binary) is None for binary in ("smbd", "testparm", "systemctl")):
            return False
        if (
            not _config_has_managed_include()
            or _read_regular_text(MANAGED_CONFIG, missing_ok=True) is None
        ):
            return False
        if not _samba_modules_available():
            return False
        _load_entries(strict=True)
        _run_checked("testparm", "-s", str(SAMBA_CONFIG), timeout=15.0)
        _run_checked("systemctl", "is-active", "--quiet", "smbd.service", timeout=10.0)
    except OSError:
        return False
    return True


def _require_ready() -> None:
    if not capability_available():
        raise OSError(
            "native Time Machine requires the managed Samba include and fruit VFS modules"
        )


def _testparm_value(section: str, parameter: str) -> str:
    return _run_checked(
        "testparm",
        "-s",
        f"--section-name={section}",
        f"--parameter-name={parameter}",
        str(SAMBA_CONFIG),
        timeout=15.0,
    ).strip()


def _verify_live_entry(entry: dict[str, Any]) -> None:
    section = entry["name"]
    exact = {
        "path": entry["path"],
        "valid users": entry["owner"],
    }
    for parameter, expected in exact.items():
        if _testparm_value(section, parameter) != expected:
            raise OSError(f"live Time Machine share has unexpected {parameter}")
    yes_no = {
        "browseable": True,
        "read only": False,
        "guest ok": False,
        "fruit:time machine": True,
    }
    for parameter, expected in yes_no.items():
        observed = _testparm_value(section, parameter).casefold()
        if (observed in {"yes", "true", "1"}) != expected:
            raise OSError(f"live Time Machine share has unexpected {parameter}")
    modules = _testparm_value(section, "vfs objects").split()
    if not set(_VFS_MODULES).issubset(modules):
        raise OSError("live Time Machine share is missing required fruit VFS modules")
    limit = _testparm_value(section, "fruit:time machine max size").casefold()
    expected_gib = entry["maximumBytes"] // 1024**3
    if limit not in {f"{expected_gib}g", str(entry["maximumBytes"])}:
        raise OSError("live Time Machine share has an unexpected size limit")


def _verify_live_absent(name: str) -> None:
    output = _run_checked("testparm", "-s", str(SAMBA_CONFIG), timeout=15.0)
    if re.search(rf"(?mi)^\[{re.escape(name)}\]\s*$", output):
        raise OSError("Time Machine share remained in effective Samba configuration")


def _public_entry(entry: dict[str, Any], *, folder_status: str | None = None) -> dict[str, Any]:
    projected = {
        "sharedFolderRef": entry["sharedFolderRef"],
        "name": entry["name"],
        "owner": entry["owner"],
        "maximumBytes": entry["maximumBytes"],
    }
    if folder_status is not None:
        projected["status"] = folder_status
    return projected


def status() -> dict[str, Any]:
    entries = _load_entries()
    storage = _storage()
    shares = []
    for entry in entries:
        try:
            folder = storage._resolve_shared_folder(entry["sharedFolderRef"])
            folder_status = storage._native_registered_folder_status(folder)
        except (OSError, ValueError):
            folder_status = "UNAVAILABLE"
        shares.append(_public_entry(entry, folder_status=folder_status))
    return {
        "schema": "echo.storage.time-machine-status.v1",
        "enabled": bool(entries),
        "available": capability_available(),
        "shares": shares,
        "source": "native",
        "readOnly": True,
    }


def _build_plan(desired: dict[str, Any]) -> dict[str, Any]:
    _require_ready()
    storage = _storage()
    folder = storage._resolve_shared_folder(desired["sharedFolderRef"])
    folder_status = storage._native_registered_folder_status(folder)
    path = storage._native_registered_path(folder)
    entries = _load_entries(strict=True)
    config_text = _read_regular_text(MANAGED_CONFIG)
    existing = next(
        (entry for entry in entries if entry["sharedFolderRef"] == desired["sharedFolderRef"]),
        None,
    )
    if desired["enabled"]:
        if folder_status != "MOUNTED":
            raise ValueError("Time Machine folder volume is not mounted as a writable NAS target")
        if storage._constrained_user_snapshot(desired["owner"]) is None:
            raise ValueError("Time Machine owner must be an existing managed NAS user")
        if storage._smb_usershare_info(str(folder["name"])) is not None:
            raise ValueError("disable the ordinary SMB share before enabling Time Machine")
        if any(
            entry.get("sharedFolderRef") == desired["sharedFolderRef"]
            for entry in storage._nfs_exports_load(strict=True, allow_unmounted=True)
        ):
            raise ValueError("remove NFS rules before enabling Time Machine")
        if existing is None and not storage._directory_is_empty(
            storage._native_folder_path(folder)
        ):
            raise ValueError("a new Time Machine destination must use a dedicated empty folder")

    current = (
        {"enabled": False, "owner": None, "maximumBytes": None}
        if existing is None
        else {
            "enabled": True,
            "owner": existing["owner"],
            "maximumBytes": existing["maximumBytes"],
        }
    )
    after = {
        "enabled": desired["enabled"],
        "owner": desired["owner"] if desired["enabled"] else current["owner"],
        "maximumBytes": desired["maximumBytes"] if desired["enabled"] else current["maximumBytes"],
    }
    changes = [
        {"field": field, "before": current[field], "after": value}
        for field, value in after.items()
        if current[field] != value
    ]
    if existing is None:
        operation = "create" if desired["enabled"] else "none"
    elif desired["enabled"]:
        operation = "update" if changes else "none"
    else:
        operation = "remove"
    base_revision = storage._canonical_hash(
        {
            "folder": {
                "uuid": folder["uuid"],
                "name": folder["name"],
                "path": str(path),
                "status": folder_status,
            },
            "config": config_text,
        }
    )
    plan_id = storage._canonical_hash(
        {
            "schema": TIME_MACHINE_PLAN_SCHEMA,
            "baseRevision": base_revision,
            "desired": desired,
            "operation": operation,
        }
    )
    return {
        "schema": TIME_MACHINE_PLAN_SCHEMA,
        "planId": plan_id,
        "baseRevision": base_revision,
        "operation": operation,
        "requiresApproval": operation != "none",
        "sharedFolder": {
            "uuid": folder["uuid"],
            "name": folder["name"],
            "status": folder_status,
        },
        "desired": desired,
        "changes": changes,
        "safety": {
            "protocol": "smb3-vfs-fruit",
            "authentication": "singleManagedNasUser",
            "guestAccess": "denied",
            "directory": "dedicatedAndEmptyOnCreate",
            "dataOnDisable": "preserved",
            "conflictingShares": "mustBeAbsent",
            "rollback": "configAndSmbdReload",
        },
        "source": "native",
    }


def plan_time_machine(desired_state: dict[str, Any]) -> dict[str, Any]:
    desired = validate_time_machine_desired(dict(desired_state))
    with _storage()._registry_transaction():
        return _build_plan(desired)


def apply_time_machine(desired_state: dict[str, Any], plan_id: str) -> dict[str, Any]:
    desired = validate_time_machine_desired(dict(desired_state))
    storage = _storage()
    with storage._registry_transaction():
        plan = _build_plan(desired)
        if plan["planId"] != plan_id:
            raise ValueError("Time Machine plan is stale; preview the change again")
        entries = _load_entries(strict=True)
        old_config = _read_regular_text(MANAGED_CONFIG)
        existing = next(
            (entry for entry in entries if entry["sharedFolderRef"] == desired["sharedFolderRef"]),
            None,
        )
        if plan["operation"] == "none":
            if desired["enabled"]:
                assert existing is not None
                _verify_live_entry(existing)
            else:
                _verify_live_absent(plan["sharedFolder"]["name"])
            return {**plan, "applied": False, "verified": True, "dataPreserved": True}

        wanted = [
            entry for entry in entries if entry["sharedFolderRef"] != desired["sharedFolderRef"]
        ]
        replacement = _entry_for_desired(desired) if desired["enabled"] else None
        if replacement is not None:
            wanted.append(replacement)
        wanted.sort(key=lambda row: row["name"])
        try:
            storage._atomic_text_save(MANAGED_CONFIG, render_config(wanted), mode=0o644)
            _run_checked("testparm", "-s", str(SAMBA_CONFIG), timeout=15.0)
            _run_checked("systemctl", "reload", "smbd.service", timeout=30.0)
            if _load_entries(strict=True) != wanted:
                raise OSError("Time Machine configuration write-back verification failed")
            if replacement is not None:
                _verify_live_entry(replacement)
            else:
                _verify_live_absent(plan["sharedFolder"]["name"])
        except Exception as exc:
            try:
                assert old_config is not None
                storage._atomic_text_save(MANAGED_CONFIG, old_config, mode=0o644)
                _run_checked("testparm", "-s", str(SAMBA_CONFIG), timeout=15.0)
                _run_checked("systemctl", "reload", "smbd.service", timeout=30.0)
                if _read_regular_text(MANAGED_CONFIG) != old_config:
                    raise OSError("Time Machine configuration rollback was not verified")
                for old_entry in entries:
                    _verify_live_entry(old_entry)
            except Exception as rollback_exc:
                raise OSError(
                    "Time Machine update failed and rollback also failed; inspect Samba immediately"
                ) from rollback_exc
            if isinstance(exc, (OSError, ValueError)):
                raise
            raise OSError("Time Machine update failed") from exc
        return {
            **plan,
            "applied": True,
            "verified": True,
            "dataPreserved": True,
            "share": _public_entry(replacement)
            if replacement is not None
            else {"sharedFolderRef": desired["sharedFolderRef"], "removed": True},
        }


def dependency_for(shared_folder_ref: str) -> dict[str, Any] | None:
    """Return the managed dependency even while the data volume is offline."""
    return next(
        (
            entry
            for entry in _load_entries(strict=True)
            if entry["sharedFolderRef"] == shared_folder_ref
        ),
        None,
    )


def dependency_for_name(name: str) -> dict[str, Any] | None:
    """Return a managed share whose Samba service name would collide."""
    folded = name.casefold()
    return next(
        (entry for entry in _load_entries(strict=True) if entry["name"].casefold() == folded),
        None,
    )


__all__ = [
    "MANAGED_CONFIG",
    "SAMBA_CONFIG",
    "TIME_MACHINE_CAPABILITY",
    "apply_time_machine",
    "capability_available",
    "dependency_for",
    "dependency_for_name",
    "plan_time_machine",
    "render_config",
    "status",
]
