"""Read-only DLNA publication for explicitly selected native NAS shares.

ReadyMedia needs the host network for SSDP discovery.  Echo therefore keeps
it outside Docker, publishes only two fixed private-LAN ports, and gives the
daemon a mount namespace in which every native NAS root is hidden.  Selected
shares are reintroduced at UUID-derived paths with ``BindReadOnlyPaths``.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import stat
import subprocess
import sys
from pathlib import Path, PurePosixPath
from typing import Any

from appliance import native_firewall
from appliance.omv_protocol import (
    DLNA_CONTROL_CAPABILITY,
    DLNA_DESIRED_SCHEMA,
    DLNA_PLAN_SCHEMA,
    validate_dlna_desired,
)

if os.name == "posix":
    import pwd
else:  # pragma: no cover - the service is Linux-only; tests import it on Windows
    pwd = None  # type: ignore[assignment]

DLNA_CAPABILITY = DLNA_CONTROL_CAPABILITY
MANAGED_CONFIG = Path("/etc/echo-os/minidlna.conf")
MANAGED_DROP_IN = Path("/etc/systemd/system/echo-dlna.service.d/shares.conf")
SERVICE_UNIT = Path("/usr/lib/systemd/system/echo-dlna.service")
SERVICE = "echo-dlna.service"
MEDIA_ROOT = PurePosixPath("/run/echo-dlna/media")
_HEADER = "# Generated by Echo OS. Manual edits are rejected and never merged."
_METADATA_PREFIX = "# echo-os-dlna "
_SAFE_UNIT_PATH = re.compile(r"/[A-Za-z0-9._/-]+")
_MEDIA_PREFIX = {"all": "", "audio": "A,", "video": "V,", "pictures": "P,"}


def _storage() -> Any:
    from appliance import native_storage

    return native_storage


def _read_regular_text(path: Path, *, missing_ok: bool = False) -> str | None:
    try:
        info = path.lstat()
    except FileNotFoundError:
        if missing_ok:
            return None
        raise
    if not stat.S_ISREG(info.st_mode) or stat.S_ISLNK(info.st_mode):
        raise OSError(f"managed DLNA file is not a regular file: {path}")
    try:
        return path.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as exc:
        raise OSError(f"managed DLNA file is unreadable: {path}") from exc


def _safe_unit_path(path: Path) -> str:
    text = str(path)
    if (
        not path.is_absolute()
        or _SAFE_UNIT_PATH.fullmatch(text) is None
        or "//" in text
        or any(part in {".", ".."} for part in path.parts)
    ):
        raise ValueError("DLNA share path cannot be represented safely in a systemd bind mount")
    return text


def _target_path(folder_ref: str) -> str:
    return str(MEDIA_ROOT / folder_ref)


def _entry_for_desired(desired: dict[str, Any]) -> dict[str, Any]:
    storage = _storage()
    folder = storage._resolve_shared_folder(desired["sharedFolderRef"])
    source = storage._native_registered_path(folder)
    name = storage._registered_relative_name(folder, strict=True)
    assert name is not None
    return {
        "sharedFolderRef": desired["sharedFolderRef"],
        "name": name,
        "sourcePath": _safe_unit_path(source),
        "mediaType": desired["mediaType"],
    }


def _validate_entry(value: Any) -> dict[str, Any]:
    if not isinstance(value, dict) or set(value) != {
        "sharedFolderRef",
        "name",
        "sourcePath",
        "mediaType",
    }:
        raise OSError("Echo-managed DLNA configuration has invalid metadata")
    try:
        desired = validate_dlna_desired(
            {
                "schema": DLNA_DESIRED_SCHEMA,
                "sharedFolderRef": value.get("sharedFolderRef"),
                "enabled": True,
                "mediaType": value.get("mediaType"),
            }
        )
        expected = _entry_for_desired(desired)
    except (OSError, ValueError) as exc:
        raise OSError("Echo-managed DLNA configuration has stale or unsafe metadata") from exc
    if value != expected:
        raise OSError("Echo-managed DLNA configuration has stale or unsafe metadata")
    return expected


def render_config(entries: list[dict[str, Any]]) -> str:
    normalized = sorted(
        (_validate_entry(entry) for entry in entries), key=lambda row: row["sharedFolderRef"]
    )
    identifiers = [entry["sharedFolderRef"] for entry in normalized]
    if len(identifiers) != len(set(identifiers)):
        raise OSError("Echo-managed DLNA configuration contains duplicate shares")
    lines = [
        _HEADER,
        "port=8200",
        "friendly_name=Echo OS",
        "db_dir=/var/lib/echo-dlna",
        "inotify=yes",
        "wide_links=no",
        "strict_dlna=no",
        "max_connections=32",
        "notify_interval=900",
        "root_container=B",
        "log_level=general,artwork,database,inotify,scanner,metadata,http,ssdp=warn",
    ]
    for entry in normalized:
        metadata = json.dumps(entry, ensure_ascii=True, sort_keys=True, separators=(",", ":"))
        lines.extend(
            [
                f"{_METADATA_PREFIX}{metadata}",
                f"media_dir={_MEDIA_PREFIX[entry['mediaType']]}{_target_path(entry['sharedFolderRef'])}",
            ]
        )
    return "\n".join(lines) + "\n"


def render_drop_in(entries: list[dict[str, Any]]) -> str:
    normalized = sorted(
        (_validate_entry(entry) for entry in entries), key=lambda row: row["sharedFolderRef"]
    )
    lines = [_HEADER, "[Service]", "BindReadOnlyPaths="]
    for entry in normalized:
        lines.append(
            f"BindReadOnlyPaths={entry['sourcePath']}:{_target_path(entry['sharedFolderRef'])}"
        )
    return "\n".join(lines) + "\n"


def _load_entries(*, strict: bool = False) -> list[dict[str, Any]]:
    try:
        config = _read_regular_text(MANAGED_CONFIG, missing_ok=True)
        drop_in = _read_regular_text(MANAGED_DROP_IN, missing_ok=True)
        if config is None and drop_in is None:
            return []
        if config is None or drop_in is None:
            raise OSError("Echo-managed DLNA configuration is incomplete")
        raw = [
            json.loads(line[len(_METADATA_PREFIX) :])
            for line in config.splitlines()
            if line.startswith(_METADATA_PREFIX)
        ]
        entries = sorted(
            (_validate_entry(entry) for entry in raw), key=lambda row: row["sharedFolderRef"]
        )
        if not entries or config != render_config(entries) or drop_in != render_drop_in(entries):
            raise OSError("Echo-managed DLNA configuration was modified outside Echo OS")
        return entries
    except (OSError, ValueError, TypeError, json.JSONDecodeError) as exc:
        if strict:
            if isinstance(exc, OSError):
                raise
            raise OSError("Echo-managed DLNA configuration is unreadable") from exc
        return []


def _run(*args: str, timeout: float = 30.0, check: bool = True) -> subprocess.CompletedProcess[str]:
    try:
        completed = subprocess.run(
            list(args), capture_output=True, text=True, timeout=timeout, check=False
        )
    except (OSError, subprocess.SubprocessError) as exc:
        raise OSError(f"DLNA command failed to start: {' '.join(args)}") from exc
    if check and completed.returncode != 0:
        detail = (completed.stderr or completed.stdout).strip() or f"exit {completed.returncode}"
        raise OSError(f"{args[0]} failed: {detail}")
    return completed


def _service_state() -> dict[str, bool]:
    enabled = _run("systemctl", "is-enabled", "--quiet", SERVICE, check=False).returncode == 0
    active = _run("systemctl", "is-active", "--quiet", SERVICE, check=False).returncode == 0
    return {"enabled": enabled, "active": active}


def capability_available() -> bool:
    if any(shutil.which(name) is None for name in ("firewall-cmd", "minidlnad", "systemctl")):
        return False
    if not SERVICE_UNIT.is_file() or SERVICE_UNIT.is_symlink():
        return False
    if os.name == "posix":
        try:
            assert pwd is not None
            pwd.getpwnam("minidlna")
        except KeyError:
            return False
    try:
        _load_entries(strict=True)
    except OSError:
        return False
    return True


def _require_ready() -> None:
    if not capability_available():
        raise OSError("native DLNA requires ReadyMedia, firewalld and the hardened Echo service")


def firewall_required() -> bool:
    return bool(_load_entries(strict=True))


def status() -> dict[str, Any]:
    entries = _load_entries()
    service = _service_state() if shutil.which("systemctl") else {"enabled": False, "active": False}
    storage = _storage()
    shares: list[dict[str, Any]] = []
    for entry in entries:
        try:
            folder = storage._resolve_shared_folder(entry["sharedFolderRef"])
            folder_status = storage._native_registered_folder_status(folder)
        except (OSError, ValueError):
            folder_status = "UNAVAILABLE"
        shares.append(
            {
                "sharedFolderRef": entry["sharedFolderRef"],
                "name": entry["name"],
                "mediaType": entry["mediaType"],
                "status": folder_status,
            }
        )
    return {
        "schema": "echo.storage.dlna-status.v1",
        "enabled": bool(entries) and service["enabled"],
        "active": bool(entries) and service["active"],
        "available": capability_available(),
        "port": 8200,
        "shares": shares,
        "source": "native",
        "readOnly": True,
    }


def _build_plan(desired: dict[str, Any]) -> dict[str, Any]:
    _require_ready()
    storage = _storage()
    folder = storage._resolve_shared_folder(desired["sharedFolderRef"])
    folder_status = storage._native_registered_folder_status(folder)
    if desired["enabled"] and folder_status != "MOUNTED":
        raise ValueError("DLNA folder volume is not mounted as a readable NAS target")
    entries = _load_entries(strict=True)
    existing = next(
        (entry for entry in entries if entry["sharedFolderRef"] == desired["sharedFolderRef"]),
        None,
    )
    current = {
        "enabled": existing is not None,
        "mediaType": existing["mediaType"] if existing else None,
    }
    after = {
        "enabled": desired["enabled"],
        "mediaType": desired["mediaType"] if desired["enabled"] else current["mediaType"],
    }
    changes = [
        {"field": field, "before": current[field], "after": value}
        for field, value in after.items()
        if current[field] != value
    ]
    if existing is None:
        operation = "create" if desired["enabled"] else "none"
    elif desired["enabled"]:
        operation = "update" if changes else "none"
    else:
        operation = "remove"
    base_revision = storage._canonical_hash(
        {
            "folder": {
                "uuid": folder["uuid"],
                "name": folder["name"],
                "status": folder_status,
                "path": str(storage._native_registered_path(folder)),
            },
            "config": _read_regular_text(MANAGED_CONFIG, missing_ok=True),
            "dropIn": _read_regular_text(MANAGED_DROP_IN, missing_ok=True),
            "service": _service_state(),
        }
    )
    plan_id = storage._canonical_hash(
        {
            "schema": DLNA_PLAN_SCHEMA,
            "baseRevision": base_revision,
            "desired": desired,
            "operation": operation,
        }
    )
    return {
        "schema": DLNA_PLAN_SCHEMA,
        "planId": plan_id,
        "baseRevision": base_revision,
        "operation": operation,
        "requiresApproval": operation != "none",
        "sharedFolder": {"uuid": folder["uuid"], "name": folder["name"], "status": folder_status},
        "desired": desired,
        "changes": changes,
        "safety": {
            "contentAccess": "selectedShareReadOnlyBind",
            "otherNasRoots": "inaccessible",
            "network": "privateLanTcp8200Udp1900Only",
            "wideSymlinks": "disabled",
            "privileges": "dedicatedMinidlnaUserNoCapabilities",
            "dataOnDisable": "preserved",
            "rollback": "configDropInServiceAndFirewall",
        },
        "source": "native",
    }


def plan_dlna(desired_state: dict[str, Any]) -> dict[str, Any]:
    desired = validate_dlna_desired(dict(desired_state))
    with _storage()._registry_transaction():
        return _build_plan(desired)


def _write_state(entries: list[dict[str, Any]]) -> None:
    storage = _storage()
    if not entries:
        storage._restore_managed_text(MANAGED_CONFIG, None, mode=0o644)
        storage._restore_managed_text(MANAGED_DROP_IN, None, mode=0o644)
        return
    storage._atomic_text_save(MANAGED_CONFIG, render_config(entries), mode=0o644)
    storage._atomic_text_save(MANAGED_DROP_IN, render_drop_in(entries), mode=0o644)


def _set_service(*, enabled: bool, active: bool) -> None:
    _run("systemctl", "daemon-reload", timeout=60.0)
    if enabled:
        _run("systemctl", "enable", SERVICE, timeout=30.0)
    else:
        _run("systemctl", "disable", SERVICE, timeout=30.0, check=False)
    if active:
        _run("systemctl", "restart", SERVICE, timeout=60.0)
    else:
        _run("systemctl", "stop", SERVICE, timeout=60.0, check=False)


def _verify_live(entries: list[dict[str, Any]]) -> None:
    state = _service_state()
    if entries:
        if state != {"enabled": True, "active": True}:
            raise OSError("DLNA service is not enabled and active")
        if _load_entries(strict=True) != entries:
            raise OSError("DLNA configuration write-back verification failed")
    elif state["enabled"] or state["active"]:
        raise OSError("DLNA service remained enabled after the last share was removed")
    native_firewall.verify_dlna(enabled=bool(entries))


def apply_dlna(desired_state: dict[str, Any], plan_id: str) -> dict[str, Any]:
    desired = validate_dlna_desired(dict(desired_state))
    storage = _storage()
    with storage._registry_transaction():
        plan = _build_plan(desired)
        if plan["planId"] != plan_id:
            raise ValueError("DLNA plan is stale; preview the change again")
        entries = _load_entries(strict=True)
        if plan["operation"] == "none":
            _verify_live(entries)
            return {**plan, "applied": False, "verified": True, "dataPreserved": True}

        old_config = _read_regular_text(MANAGED_CONFIG, missing_ok=True)
        old_drop_in = _read_regular_text(MANAGED_DROP_IN, missing_ok=True)
        old_service = _service_state()
        wanted = [
            entry for entry in entries if entry["sharedFolderRef"] != desired["sharedFolderRef"]
        ]
        replacement = _entry_for_desired(desired) if desired["enabled"] else None
        if replacement is not None:
            wanted.append(replacement)
        wanted.sort(key=lambda row: row["sharedFolderRef"])
        try:
            if wanted:
                _write_state(wanted)
                native_firewall.sync_dlna(enabled=True)
                _set_service(enabled=True, active=True)
            else:
                _set_service(enabled=False, active=False)
                native_firewall.sync_dlna(enabled=False)
                _write_state([])
                _run("systemctl", "daemon-reload", timeout=60.0)
            _verify_live(wanted)
        except Exception as exc:
            try:
                storage._restore_managed_text(MANAGED_CONFIG, old_config, mode=0o644)
                storage._restore_managed_text(MANAGED_DROP_IN, old_drop_in, mode=0o644)
                native_firewall.sync_dlna(enabled=bool(entries))
                _set_service(enabled=old_service["enabled"], active=old_service["active"])
                _verify_live(entries)
            except Exception as rollback_exc:
                raise OSError(
                    "DLNA update failed and rollback also failed; inspect ReadyMedia immediately"
                ) from rollback_exc
            if isinstance(exc, (OSError, ValueError)):
                raise
            raise OSError("DLNA update failed") from exc
        return {
            **plan,
            "applied": True,
            "verified": True,
            "dataPreserved": True,
            "share": (
                {
                    "sharedFolderRef": replacement["sharedFolderRef"],
                    "name": replacement["name"],
                    "mediaType": replacement["mediaType"],
                }
                if replacement is not None
                else {"sharedFolderRef": desired["sharedFolderRef"], "removed": True}
            ),
        }


def dependency_for(shared_folder_ref: str) -> dict[str, Any] | None:
    return next(
        (
            entry
            for entry in _load_entries(strict=True)
            if entry["sharedFolderRef"] == shared_folder_ref
        ),
        None,
    )


def dependency_for_name(name: str) -> dict[str, Any] | None:
    folded = name.casefold()
    return next(
        (entry for entry in _load_entries(strict=True) if entry["name"].casefold() == folded),
        None,
    )


def verify_start() -> dict[str, Any]:
    """Fail closed before ReadyMedia enters its long-lived unprivileged process."""

    _require_ready()
    entries = _load_entries(strict=True)
    if not entries:
        raise OSError("DLNA service has no approved media shares")
    storage = _storage()
    for entry in entries:
        folder = storage._resolve_shared_folder(entry["sharedFolderRef"])
        live_path = storage._native_folder_path(folder)
        if _safe_unit_path(live_path) != entry["sourcePath"]:
            raise OSError("DLNA share no longer resolves to its approved mounted directory")
    native_firewall.verify_dlna(enabled=True)
    return {"shares": len(entries), "firewall": "verified"}


def _main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Verify Echo's read-only DLNA service state")
    parser.add_argument("command", choices=("verify-start",))
    args = parser.parse_args(argv)
    if args.command == "verify-start":
        try:
            result = verify_start()
        except (OSError, ValueError) as exc:
            print(f"Echo DLNA start verification failed: {exc}", file=sys.stderr)
            return 1
        print(f"ECHO_DLNA_READY shares={result['shares']} firewall=verified")
    return 0


if __name__ == "__main__":  # pragma: no cover - exercised by the Linux service
    raise SystemExit(_main())


__all__ = [
    "DLNA_CAPABILITY",
    "apply_dlna",
    "capability_available",
    "dependency_for",
    "dependency_for_name",
    "firewall_required",
    "plan_dlna",
    "render_config",
    "render_drop_in",
    "status",
    "verify_start",
]
