apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: echo-agent-data
  namespace: echo-agent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: echo-redis-data
  namespace: echo-agent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
