from __future__ import annotations

from ..openai_formatting import chat_completion_envelope as _chat_completion_envelope
from .context_manager import (
    _build_messages_for_llm,
    _conversation_messages_for_model,
    _conversation_messages_payload,
    _extract_goal,
    _interaction_profile_prompt,
    _message_content_text,
    _normalize_conversation_messages,
    _profile_memories_payload,
    _render_conversation_history,
    _runtime_soul_for_agent,
)
from .request_parser import _model_supports_thinking, _resolve_actor
from .response_formatter import (
    _assistant_text_from_trajectory,
    _format_research_report_fallback,
    _is_research_report_context,
    _looks_like_complete_research_report,
    _markdown_table_cell,
    _research_context_mode,
    _research_report_section_score,
)
from .stream_handler import (
    _commit_direct_llm_cost,
    _direct_llm_fallback,
    _direct_llm_fallback_impl,
    _direct_llm_fallback_with_usage,
    _reflex_stream_frames,
    _stream_chat,
    _stream_chat_wrapped,
    _stream_direct_llm_fallback,
)
from .tool_converter import (
    _clean_report_text,
    _react_action_args,
    _react_action_name,
    _react_observation_payload,
    _trajectory_research_evidence,
    _trajectory_tool_lines,
)

__all__ = [
    "_assistant_text_from_trajectory",
    "_build_messages_for_llm",
    "_chat_completion_envelope",
    "_clean_report_text",
    "_commit_direct_llm_cost",
    "_conversation_messages_for_model",
    "_conversation_messages_payload",
    "_direct_llm_fallback",
    "_direct_llm_fallback_impl",
    "_direct_llm_fallback_with_usage",
    "_extract_goal",
    "_format_research_report_fallback",
    "_interaction_profile_prompt",
    "_is_research_report_context",
    "_looks_like_complete_research_report",
    "_markdown_table_cell",
    "_message_content_text",
    "_model_supports_thinking",
    "_normalize_conversation_messages",
    "_profile_memories_payload",
    "_react_action_args",
    "_react_action_name",
    "_react_observation_payload",
    "_reflex_stream_frames",
    "_render_conversation_history",
    "_research_context_mode",
    "_research_report_section_score",
    "_resolve_actor",
    "_runtime_soul_for_agent",
    "_stream_chat",
    "_stream_chat_wrapped",
    "_stream_direct_llm_fallback",
    "_trajectory_research_evidence",
    "_trajectory_tool_lines",
]
