#!/usr/bin/env python3
"""Verify the immutable Python/resources/Codex tree for native Echo OS."""

from __future__ import annotations

import argparse
import ast
import hashlib
import importlib.metadata
import json
import os
import stat
import struct
import sys
from pathlib import Path
from typing import Any

SCHEMA_VERSION = 4
MANIFEST_NAME = "native-runtime.json"
MAX_JSON_BYTES = 4 * 1024 * 1024
AGENT_RECOVERY_SURFACE_SCHEMA = "echo.agent_recovery_surface.v1"
AGENT_IDENTITY_SURFACE_SCHEMA = "echo.agent_runtime_identity.v1"
HEALTH_PATH = "/api/health"
RECOVERY_QUEUE_PATH = "/api/task-runs/recovery-queue"
RESUME_EXECUTION_PATH = "/api/task-runs/{task_id}/resume-execution"
MACHO_MAGICS = {
    b"\xfe\xed\xfa\xce",
    b"\xce\xfa\xed\xfe",
    b"\xfe\xed\xfa\xcf",
    b"\xcf\xfa\xed\xfe",
    b"\xca\xfe\xba\xbe",
    b"\xbe\xba\xfe\xca",
}


class RuntimeError(ValueError):
    """The staged native Agent runtime is incomplete or internally mixed."""


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _json(path: Path) -> dict[str, Any]:
    if path.is_symlink() or not path.is_file():
        raise RuntimeError(f"JSON input must be a regular file: {path}")
    size = path.stat().st_size
    if not 1 <= size <= MAX_JSON_BYTES:
        raise RuntimeError(f"JSON input is empty or oversized: {path}")
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as error:
        raise RuntimeError(f"invalid JSON input: {path}") from error
    if not isinstance(value, dict):
        raise RuntimeError(f"JSON input must contain an object: {path}")
    return value


def _tree_digest(root: Path) -> dict[str, Any]:
    if root.is_symlink() or not root.is_dir():
        raise RuntimeError(f"runtime root must be a real directory: {root}")
    digest = hashlib.sha256()
    count = 0
    total = 0
    for path in sorted(root.rglob("*"), key=lambda item: item.as_posix()):
        relative = path.relative_to(root).as_posix()
        if relative == MANIFEST_NAME:
            continue
        info = path.lstat()
        if stat.S_ISDIR(info.st_mode):
            continue
        if not stat.S_ISREG(info.st_mode) or path.is_symlink():
            raise RuntimeError(f"runtime tree contains a link or special file: {relative}")
        mode = stat.S_IMODE(info.st_mode)
        if mode & 0o022 or mode & 0o6000:
            raise RuntimeError(f"runtime file has unsafe permissions: {relative} mode={mode:o}")
        if relative.endswith((".pyc", ".pyo")) or "/__pycache__/" in f"/{relative}/":
            raise RuntimeError(f"runtime tree contains generated bytecode: {relative}")
        with path.open("rb") as handle:
            header = handle.read(20)
        if header[:4] in MACHO_MAGICS:
            raise RuntimeError(f"runtime tree contains a macOS binary: {relative}")
        if header.startswith(b"\x7fELF"):
            if len(header) < 20 or header[4] != 2 or header[5] != 1:
                raise RuntimeError(f"runtime ELF is not little-endian ELF64: {relative}")
            machine = struct.unpack("<H", header[18:20])[0]
            if machine != 62:
                raise RuntimeError(f"runtime ELF is not x86-64: {relative} e_machine={machine}")
        elif relative.endswith((".so", ".dylib")) or ".so." in relative:
            raise RuntimeError(f"native library is not an ELF object: {relative}")
        file_hash = _sha256(path)
        digest.update(relative.encode("utf-8"))
        digest.update(b"\0")
        digest.update(f"{mode:o}\0{info.st_size}\0{file_hash}\n".encode("ascii"))
        count += 1
        total += info.st_size
    if count == 0:
        raise RuntimeError("runtime tree contains no files")
    return {"file_count": count, "size": total, "tree_sha256": digest.hexdigest()}


def _verify_partial(
    root: Path,
    *,
    kind: str,
    source: dict[str, Any],
    artifact: dict[str, Any],
) -> None:
    partial = _json(root / "agent-build.json")
    if (
        partial.get("schema_version") != 2
        or partial.get("kind") != kind
        or partial.get("source") != source
        or partial.get("artifact") != artifact
    ):
        raise RuntimeError(f"Agent {kind} does not match the assembled bundle")


def _metadata_identity(site_packages: Path, distribution_name: str) -> tuple[str, str]:
    canonical = distribution_name.lower().replace("-", "_").replace(".", "_")
    matches: list[Path] = []
    for candidate in site_packages.glob("*.dist-info"):
        prefix = candidate.name.rsplit(".dist-info", 1)[0].rsplit("-", 1)[0]
        if prefix.lower().replace("-", "_").replace(".", "_") == canonical:
            matches.append(candidate)
    if len(matches) != 1:
        raise RuntimeError(f"expected one installed Agent distribution, found {len(matches)}")
    metadata = matches[0] / "METADATA"
    if metadata.is_symlink() or not metadata.is_file():
        raise RuntimeError("installed Agent distribution has no regular METADATA")
    name = ""
    version = ""
    for line in metadata.read_text(encoding="utf-8", errors="strict").splitlines():
        if line.startswith("Name: "):
            name = line[6:].strip()
        elif line.startswith("Version: "):
            version = line[9:].strip()
        if name and version:
            break
    return name, version


def _python_source(path: Path) -> tuple[str, ast.Module]:
    if path.is_symlink() or not path.is_file():
        raise RuntimeError(f"required Agent Python source is missing: {path}")
    if not 1 <= path.stat().st_size <= MAX_JSON_BYTES:
        raise RuntimeError(f"required Agent Python source is empty or oversized: {path}")
    try:
        source = path.read_text(encoding="utf-8", errors="strict")
        tree = ast.parse(source, filename=str(path))
    except (OSError, UnicodeError, SyntaxError) as error:
        raise RuntimeError(f"required Agent Python source cannot be parsed: {path}") from error
    return source, tree


def _decorated_routes(tree: ast.Module) -> set[tuple[str, str]]:
    routes: set[tuple[str, str]] = set()
    for node in ast.walk(tree):
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        for decorator in node.decorator_list:
            if (
                not isinstance(decorator, ast.Call)
                or not isinstance(decorator.func, ast.Attribute)
                or decorator.func.attr not in {"get", "post", "put", "patch", "delete"}
                or not decorator.args
                or not isinstance(decorator.args[0], ast.Constant)
                or not isinstance(decorator.args[0].value, str)
            ):
                continue
            routes.add((decorator.func.attr.upper(), decorator.args[0].value))
    return routes


def _verify_agent_recovery_surface(root: Path) -> dict[str, Any]:
    gateway_path = root / "site-packages/runtime/sensing/gateway/task_runs_router.py"
    analysis_path = root / "site-packages/runtime/platform/process/_task_supervisor_analysis.py"
    gateway_source, gateway_tree = _python_source(gateway_path)
    analysis_source, _analysis_tree = _python_source(analysis_path)
    routes = _decorated_routes(gateway_tree)
    required = {
        ("GET", RECOVERY_QUEUE_PATH),
        ("POST", RESUME_EXECUTION_PATH),
    }
    missing = sorted(required - routes)
    if missing:
        formatted = ", ".join(f"{method} {path}" for method, path in missing)
        raise RuntimeError(f"Agent runtime lacks required recovery routes: {formatted}")
    resume_schema = next(
        (
            schema
            for schema in (
                "echo.task_run_resume_execution.v1",
                "echo.task_run_resume_execution.v1",
            )
            if schema in gateway_source
        ),
        None,
    )
    if resume_schema is None:
        raise RuntimeError("Agent resume route lacks its required response schema")
    recovery_schema = next(
        (
            schema
            for schema in (
                "echo.task_recovery_queue.v1",
                "echo.task_recovery_queue.v1",
            )
            if schema in analysis_source
        ),
        None,
    )
    if recovery_schema is None:
        raise RuntimeError("Agent recovery queue lacks its required response schema")
    return {
        "schema": AGENT_RECOVERY_SURFACE_SCHEMA,
        "recovery_queue": {
            "method": "GET",
            "path": RECOVERY_QUEUE_PATH,
            "response_schema": recovery_schema,
        },
        "resume_execution": {
            "method": "POST",
            "path": RESUME_EXECUTION_PATH,
            "response_schema": resume_schema,
        },
    }


def _verify_agent_identity_surface(root: Path) -> dict[str, Any]:
    health_path = root / "site-packages/runtime/platform/ui/health_router.py"
    health_source, health_tree = _python_source(health_path)
    if ("GET", HEALTH_PATH) not in _decorated_routes(health_tree):
        raise RuntimeError("Agent runtime lacks GET /api/health")
    required_markers = (
        '"runtime": _runtime_identity()',
        '"version": __version__',
        '"sourceId"',
        '"verifiedBundle"',
    )
    missing = [marker for marker in required_markers if marker not in health_source]
    identity_families = (
        (
            '"name": "echo-agent-runtime"',
            '"ECHO_RUNTIME_SOURCE_ID"',
            '"ECHO_RUNTIME_BUNDLE_VERIFIED"',
        ),
        (
            '"name": "echo-agent-runtime"',
            '"ECHO_RUNTIME_SOURCE_ID"',
            '"ECHO_RUNTIME_BUNDLE_VERIFIED"',
        ),
    )
    if not any(all(marker in health_source for marker in family) for family in identity_families):
        missing.append("one complete supported runtime identity family")
    if missing:
        raise RuntimeError(
            "Agent health endpoint lacks the verified runtime identity contract: "
            + ", ".join(missing)
        )
    return {
        "schema": AGENT_IDENTITY_SURFACE_SCHEMA,
        "health": {"method": "GET", "path": HEALTH_PATH},
        "fields": ["name", "version", "sourceId", "verifiedBundle"],
    }


def _verify_codex(root: Path, expected_version: str) -> dict[str, str]:
    codex_root = root / "codex"
    manifest = _json(codex_root / "echo-codex-bundle.json")
    if (
        manifest.get("schema") != "echo.codex_bundle.v1"
        or manifest.get("package") != "@openai/codex"
        or manifest.get("version") != expected_version
        or manifest.get("platformPackage") != "@openai/codex-linux-x64"
        or manifest.get("target") != "x86_64-unknown-linux-musl"
        or manifest.get("fileHashPhase") != "pre-package"
    ):
        raise RuntimeError("Codex bundle identity does not match the Agent/runtime target")
    files = manifest.get("files")
    if not isinstance(files, dict) or not files:
        raise RuntimeError("Codex bundle has no verified file map")
    for relative, expected_hash in files.items():
        if (
            not isinstance(relative, str)
            or not isinstance(expected_hash, str)
            or len(expected_hash) != 64
            or relative.startswith("/")
            or ".." in Path(relative).parts
        ):
            raise RuntimeError("Codex bundle contains an unsafe file-map entry")
        path = codex_root / relative
        if path.is_symlink() or not path.is_file() or _sha256(path) != expected_hash:
            raise RuntimeError(f"Codex bundle file hash mismatch: {relative}")
    executable = codex_root / "bin/codex"
    if not executable.is_file() or not os.access(executable, os.X_OK):
        raise RuntimeError("Codex bundle has no executable x86-64 entrypoint")
    return {
        "version": expected_version,
        "target": "x86_64-unknown-linux-musl",
        "manifest_sha256": _sha256(codex_root / "echo-codex-bundle.json"),
        "executable_sha256": _sha256(executable),
    }


def _inputs(root: Path) -> dict[str, Any]:
    bundle = _json(root / "agent-bundle.json")
    source = bundle.get("source")
    wheel = bundle.get("wheel")
    resources = bundle.get("resources")
    codex_artifact = bundle.get("codex")
    if (
        bundle.get("schema_version") != 2
        or not isinstance(source, dict)
        or not isinstance(wheel, dict)
        or not isinstance(resources, dict)
        or not isinstance(codex_artifact, dict)
        or not source.get("source_id")
    ):
        raise RuntimeError("Agent bundle manifest is incomplete")

    dependency_identity = wheel.get("python_dependencies")
    if not isinstance(dependency_identity, dict):
        raise RuntimeError("Agent bundle does not bind its Python dependency closure")
    dependency_metadata = _json(root / "python-dependency-lock.json")
    metadata_identity = dict(dependency_metadata)
    if metadata_identity.pop("kind", None) != "echo-appliance-python-dependency-lock":
        raise RuntimeError("native dependency metadata has an invalid kind")
    metadata_identity["metadataFile"] = "python-dependency-lock.json"
    metadata_identity["metadataSha256"] = _sha256(root / "python-dependency-lock.json")
    if metadata_identity != dependency_identity:
        raise RuntimeError("native dependency metadata differs from the Agent bundle")
    if (
        dependency_identity.get("pythonVersion") != "3.12"
        or "linux/amd64" not in dependency_identity.get("platforms", [])
        or dependency_identity.get("onlyBinary") is not True
    ):
        raise RuntimeError("Agent dependency lock is not the approved binary Linux closure")
    if _sha256(root / "python-dependency-lock.json") != dependency_identity.get("metadataSha256"):
        raise RuntimeError("native dependency metadata hash mismatch")
    runtime_lock = dependency_identity.get("runtimeLock")
    if (
        not isinstance(runtime_lock, dict)
        or runtime_lock.get("file") != "runtime-requirements.lock"
    ):
        raise RuntimeError("Agent runtime dependency lock identity is invalid")
    if _sha256(root / "runtime-requirements.lock") != runtime_lock.get("sha256"):
        raise RuntimeError("native runtime dependency lock hash mismatch")

    _verify_partial(root / "resources", kind="resources", source=source, artifact=resources)
    _verify_partial(root / "codex", kind="codex", source=source, artifact=codex_artifact)
    native_config = root / "resources/config.example.yaml"
    if native_config.is_symlink() or not native_config.is_file():
        raise RuntimeError("Agent resources do not contain the source-bound native config")
    os_config = root / "native-config.yaml"
    if os_config.is_symlink() or not os_config.is_file():
        raise RuntimeError("native Agent runtime has no immutable OS policy overlay")

    distribution = str(wheel.get("distribution") or "")
    version = str(wheel.get("version") or "")
    installed_name, installed_version = _metadata_identity(root / "site-packages", distribution)
    if installed_name != distribution or installed_version != version:
        raise RuntimeError("installed Agent distribution does not match its bundle")

    codex_version = str(source.get("packaged_codex_version") or "")
    if not codex_version:
        raise RuntimeError("native Echo OS requires an Agent source that pins Codex")
    codex = _verify_codex(root, codex_version)
    for key in ("version", "target", "manifest_sha256", "executable_sha256"):
        if codex.get(key) != codex_artifact.get(key):
            raise RuntimeError(f"native Codex {key} differs from the Agent bundle")
    return {
        "bundle": bundle,
        "source": source,
        "distribution": distribution,
        "version": version,
        "codex": codex,
        "agent_recovery_surface": _verify_agent_recovery_surface(root),
        "agent_identity_surface": _verify_agent_identity_surface(root),
        "dependency_lock_sha256": runtime_lock["sha256"],
        "dependency_metadata_sha256": dependency_identity["metadataSha256"],
    }


def write_manifest(root: Path) -> dict[str, Any]:
    target = root / MANIFEST_NAME
    if target.exists() or target.is_symlink():
        raise RuntimeError(f"refusing to replace an existing native manifest: {target}")
    inputs = _inputs(root)
    manifest = {
        "schema_version": SCHEMA_VERSION,
        "kind": "echo-native-agent-runtime",
        "python_version": "3.13",
        "platform": "linux/amd64",
        "source": inputs["source"],
        "distribution": inputs["distribution"],
        "version": inputs["version"],
        "codex": inputs["codex"],
        "agent_recovery_surface": inputs["agent_recovery_surface"],
        "agent_identity_surface": inputs["agent_identity_surface"],
        "dependency_lock_sha256": inputs["dependency_lock_sha256"],
        "dependency_metadata_sha256": inputs["dependency_metadata_sha256"],
        "tree": _tree_digest(root),
    }
    target.write_text(
        json.dumps(manifest, ensure_ascii=False, sort_keys=True, separators=(",", ":")) + "\n",
        encoding="utf-8",
    )
    target.chmod(0o644)
    return manifest


def verify(root: Path, *, import_runtime: bool) -> dict[str, Any]:
    manifest = _json(root / MANIFEST_NAME)
    inputs = _inputs(root)
    expected = {
        "schema_version": SCHEMA_VERSION,
        "kind": "echo-native-agent-runtime",
        "python_version": "3.13",
        "platform": "linux/amd64",
        "source": inputs["source"],
        "distribution": inputs["distribution"],
        "version": inputs["version"],
        "codex": inputs["codex"],
        "agent_recovery_surface": inputs["agent_recovery_surface"],
        "agent_identity_surface": inputs["agent_identity_surface"],
        "dependency_lock_sha256": inputs["dependency_lock_sha256"],
        "dependency_metadata_sha256": inputs["dependency_metadata_sha256"],
        "tree": _tree_digest(root),
    }
    if manifest != expected:
        raise RuntimeError("native Agent manifest or runtime tree changed after preparation")

    if import_runtime:
        if sys.version_info[:2] != (3, 13):
            raise RuntimeError("native Agent import gate must run under CPython 3.13")
        site_packages = root / "site-packages"
        sys.path.insert(0, str(site_packages))
        os.environ.update(
            ECHO_AGENT_BUNDLE_MANIFEST=str(root / "agent-bundle.json"),
            ECHO_RESOURCES_DIR=str(root / "resources"),
            ECHO_CODEX_BUNDLE_DIR=str(root / "codex"),
            ECHO_CODEX_EXECUTABLE=str(root / "codex/bin/codex"),
            ECHO_NATIVE_OS="1",
        )
        import av  # noqa: F401
        import cryptography  # noqa: F401
        import onnxruntime  # noqa: F401
        import uvicorn  # noqa: F401

        import appliance.native_entrypoint  # noqa: F401
        import runtime.cli  # noqa: F401
        from appliance.agent_ui import agent_bundle_status
        from runtime.platform.config.loader import load_from_yaml
        from runtime.sensing.gateway.task_runs_router import create_task_runs_router

        status = agent_bundle_status()
        if not status or status.get("source_id") != inputs["source"]["source_id"]:
            raise RuntimeError("imported Agent runtime does not match the native manifest")
        installed = importlib.metadata.version(inputs["distribution"])
        if installed != inputs["version"]:
            raise RuntimeError("imported Agent distribution version mismatch")
        config = load_from_yaml(root / "native-config.yaml")
        if config.tentacle.enabled or config.intel_sources:
            raise RuntimeError("native Agent config exposes an extra listener or boot-time fetch")
        router = create_task_runs_router()
        imported_routes = {
            (str(method), str(route.path))
            for route in router.routes
            for method in (getattr(route, "methods", None) or ())
        }
        required_routes = {
            ("GET", RECOVERY_QUEUE_PATH),
            ("POST", RESUME_EXECUTION_PATH),
        }
        if not required_routes.issubset(imported_routes):
            raise RuntimeError("imported Agent runtime lacks the verified recovery surface")
    return manifest


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("root", type=Path)
    parser.add_argument("--write-manifest", action="store_true")
    parser.add_argument("--import-runtime", action="store_true")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    try:
        if args.write_manifest:
            if args.import_runtime:
                raise RuntimeError("--write-manifest and --import-runtime are mutually exclusive")
            write_manifest(args.root.resolve())
        else:
            verify(args.root.resolve(), import_runtime=args.import_runtime)
    except (OSError, UnicodeError, RuntimeError) as error:
        print(f"native Agent runtime rejected: {error}", file=sys.stderr)
        return 1
    print("ECHO_NATIVE_AGENT_RUNTIME_OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
