[network]
http-min-port = 60000
http-max-port = 65535
dns-sd = enable
interface = loopback
ipv6 = enable

[logging]
device-log = error
main-log = error
console-log = error
max-file-size = 256K
max-backup-files = 2
console-color = disable
