"""ReAct trajectory parsing + post-step quality checks.

This module is now a thin re-export hub. The responsibility-cohesive
clusters live in the ``_react_parsing_*`` submodules:
``tools`` (action/XML parsing), ``core`` (text parsing + streaming +
todo/step extraction), ``codequality`` (code-quality + payload
anti-pattern guards), ``verification`` (verification trail), and
``testquality`` (test-correctness + production-hygiene guards). The
security+quality detectors live in ``react_security_detectors``.

The public API surface is unchanged: every predicate is re-exported
here so consumers (``react_guards.py``, ``react_phase_6c.py``, the
``_react_execution_*`` modules, etc.) keep importing from
``react_parsing`` exactly as before.
"""

from __future__ import annotations

from runtime.core.cerebrum._react_parsing_codequality import (
    _count_payload_lines,
    _detect_destructive_calls_in_payload,
    _detect_secrets_in_payload,
    _is_frontend_path_outside_tsconfig,
    _load_tsconfig,
    _matches_tsconfig_pattern,
    _normalize_frontend_path,
    _payload_has_ambiguous_inflight_leader_election,
    _payload_has_broad_except_suppression,
    _payload_has_destructive_waiter_result_pop,
    _payload_has_executable_python,
    _payload_has_inflight_identity_comparison,
    _payload_has_loader_barrier_deadlock,
    _payload_has_single_pass_url_decode,
    _payload_has_sleep_call,
    _payload_has_stale_immutable_waiter_snapshot,
    _payload_has_terminal_pending_entry_leak,
    _payload_has_wait_while_lock_held,
    _payload_looks_like_path_boundary,
    _step_edits_frontend_outside_tsconfig,
    _step_introduces_broad_except_suppression,
    _step_introduces_destructive_call,
    _step_introduces_secret,
    _step_introduces_sleep,
    _step_is_full_file_rewrite_attempt,
    _step_is_oversized_edit,
    _step_is_surgical_edit_on,
    _step_payload_line_count,
    _step_replaced_code_with_comment,
    _strip_comments_for_executable_check,
    _strip_jsonc_comments,
)
from runtime.core.cerebrum._react_parsing_core import (
    _ACTION_RE,
    _FINAL_RE,
    _THOUGHT_RE,
    THOUGHT_STREAM_TAIL_MARGIN,
    _coerce_todo_action_items,
    _escape_md_brackets,
    _extract_final_answer,
    _extract_step_path,
    _extract_step_payloads,
    _has_code_write,
    _has_react_protocol_stream_prefix,
    _has_verification_requiring_code_write,
    _is_code_write_step,
    _is_verification_requiring_code_write_step,
    _latest_todo_items,
    _looks_like_protocol_leak,
    _looks_like_special_tool_envelope,
    _looks_like_unfinished_work,
    _parse_reasoning_action_fallback,
    _parse_step,
    _safe_for_streamdown,
    _split_action_lines,
    _strip_react_protocol_blocks,
    _summarize_observation,
    extract_streamable_thought,
)
from runtime.core.cerebrum._react_parsing_testquality import (
    _TEST_FUNC_RE,
    _async_body_uses_await,
    _classify_mock_only_test_body,
    _classify_test_body,
    _count_function_body_lines,
    _detect_async_without_await_in_payload,
    _detect_generic_test_names_in_payload,
    _detect_hardcoded_paths_in_payload,
    _detect_long_functions_in_payload,
    _detect_mock_only_tests_in_payload,
    _detect_no_assertion_tests_in_payload,
    _detect_weak_tests_in_payload,
    _is_abstract_or_stub_body,
    _is_generic_test_name,
    _is_meaningful_skip_reason,
    _path_is_print_exempt,
    _payload_has_log_swallow,
    _payload_has_print_call,
    _payload_has_undocumented_skip,
    _step_deleted_test_functions,
    _step_introduces_async_without_await,
    _step_introduces_generic_test_name,
    _step_introduces_hardcoded_path,
    _step_introduces_log_swallow,
    _step_introduces_long_function,
    _step_introduces_mock_only_test,
    _step_introduces_no_assertion_test,
    _step_introduces_print,
    _step_introduces_undocumented_skip,
    _step_introduces_weak_test,
    _test_body_has_assertion,
    _test_function_names,
)
from runtime.core.cerebrum._react_parsing_tools import (
    _coerce_xml_arg_value,
    _extract_tool_action_from_loose_output,
    _extract_tool_actions_from_loose_output,
    _format_action,
    _is_format_violation,
    _normalize_action_name,
    _parse_action,
    _placeholder_observation,
    _xml_args_from_body,
)
from runtime.core.cerebrum._react_parsing_verification import (
    _extract_public_signatures,
    _extract_write_payload,
    _final_answer_claims_verification,
    _has_code_verification,
    _has_language_specific_verification,
    _has_successful_verification_observation,
    _has_test_write,
    _has_wire_contract_test_write,
    _is_test_path,
    _is_third_party_module,
    _is_wire_contract_test_path,
    _is_wire_schema_path,
    _latest_verification_observation_is_red,
    _new_third_party_imports_in_payload,
    _node_command_is_verification,
    _path_language,
    _step_changed_public_signature,
    _step_command_text,
    _step_edits_wire_schema,
    _step_introduces_python_public_symbol,
    _step_introduces_third_party_imports,
    _step_is_verify,
    _step_writes_dep_manifest,
    _top_level_module,
    _verification_observation_is_red,
)

# ──────────────────────────────────────────────────────────────────
# §63-§70 — Security + quality detectors (EXTRACTED 2026-06-06)
# ──────────────────────────────────────────────────────────────────
# The following detectors have been extracted to react_security_detectors.py
# to reduce this file's size. Re-exported here for backward compatibility.
from .react_security_detectors import (  # noqa: E402, F401 — re-exported for backward compatibility
    _detect_dynamic_exec_in_payload,
    _detect_magic_numbers_in_payload,
    _detect_repeated_literals_in_payload,
    _detect_shell_injection_in_payload,
    _detect_unsafe_deser_in_payload,
    _payload_has_network_in_loop,
    _step_introduces_dynamic_exec,
    _step_introduces_magic_number,
    _step_introduces_network_in_loop,
    _step_introduces_repeated_literal,
    _step_introduces_shell_injection,
    _step_introduces_unsafe_deser,
)

__all__ = [
    # _react_parsing_core
    "_ACTION_RE",
    "_escape_md_brackets",
    "_extract_final_answer",
    "_has_react_protocol_stream_prefix",
    "_FINAL_RE",
    "_looks_like_special_tool_envelope",
    "_looks_like_protocol_leak",
    "_looks_like_unfinished_work",
    "_parse_reasoning_action_fallback",
    "_parse_step",
    "_safe_for_streamdown",
    "_split_action_lines",
    "_strip_react_protocol_blocks",
    "_summarize_observation",
    "_THOUGHT_RE",
    "extract_streamable_thought",
    "THOUGHT_STREAM_TAIL_MARGIN",
    # _react_parsing_tools
    "_coerce_xml_arg_value",
    "_extract_tool_action_from_loose_output",
    "_extract_tool_actions_from_loose_output",
    "_format_action",
    "_is_format_violation",
    "_normalize_action_name",
    "_parse_action",
    "_placeholder_observation",
    "_xml_args_from_body",
    # _react_parsing_steps
    "_coerce_todo_action_items",
    "_extract_step_path",
    "_extract_step_payloads",
    "_has_code_write",
    "_has_verification_requiring_code_write",
    "_is_code_write_step",
    "_is_verification_requiring_code_write_step",
    "_latest_todo_items",
    # _react_parsing_payload
    "_payload_has_ambiguous_inflight_leader_election",
    "_payload_has_destructive_waiter_result_pop",
    "_payload_has_inflight_identity_comparison",
    "_payload_has_loader_barrier_deadlock",
    "_payload_has_single_pass_url_decode",
    "_payload_has_stale_immutable_waiter_snapshot",
    "_payload_has_terminal_pending_entry_leak",
    "_payload_has_wait_while_lock_held",
    "_payload_looks_like_path_boundary",
    # _react_parsing_verification
    "_extract_public_signatures",
    "_extract_write_payload",
    "_final_answer_claims_verification",
    "_has_code_verification",
    "_has_language_specific_verification",
    "_has_successful_verification_observation",
    "_has_test_write",
    "_has_wire_contract_test_write",
    "_is_test_path",
    "_is_third_party_module",
    "_is_wire_contract_test_path",
    "_is_wire_schema_path",
    "_latest_verification_observation_is_red",
    "_new_third_party_imports_in_payload",
    "_node_command_is_verification",
    "_path_language",
    "_step_changed_public_signature",
    "_step_command_text",
    "_step_edits_wire_schema",
    "_step_introduces_python_public_symbol",
    "_step_introduces_third_party_imports",
    "_step_is_verify",
    "_step_writes_dep_manifest",
    "_top_level_module",
    "_verification_observation_is_red",
    # _react_parsing_codequality
    "_count_payload_lines",
    "_detect_destructive_calls_in_payload",
    "_detect_secrets_in_payload",
    "_is_frontend_path_outside_tsconfig",
    "_load_tsconfig",
    "_matches_tsconfig_pattern",
    "_normalize_frontend_path",
    "_payload_has_broad_except_suppression",
    "_payload_has_executable_python",
    "_payload_has_sleep_call",
    "_step_edits_frontend_outside_tsconfig",
    "_step_introduces_broad_except_suppression",
    "_step_introduces_destructive_call",
    "_step_introduces_secret",
    "_step_introduces_sleep",
    "_step_is_full_file_rewrite_attempt",
    "_step_is_oversized_edit",
    "_step_is_surgical_edit_on",
    "_step_payload_line_count",
    "_step_replaced_code_with_comment",
    "_strip_comments_for_executable_check",
    "_strip_jsonc_comments",
    # _react_parsing_testquality
    "_classify_mock_only_test_body",
    "_classify_test_body",
    "_detect_generic_test_names_in_payload",
    "_detect_mock_only_tests_in_payload",
    "_detect_no_assertion_tests_in_payload",
    "_detect_weak_tests_in_payload",
    "_is_generic_test_name",
    "_is_meaningful_skip_reason",
    "_payload_has_undocumented_skip",
    "_step_deleted_test_functions",
    "_step_introduces_generic_test_name",
    "_step_introduces_mock_only_test",
    "_step_introduces_no_assertion_test",
    "_step_introduces_undocumented_skip",
    "_step_introduces_weak_test",
    "_test_body_has_assertion",
    "_test_function_names",
    "_TEST_FUNC_RE",
    # _react_parsing_testquality2
    "_async_body_uses_await",
    "_count_function_body_lines",
    "_detect_async_without_await_in_payload",
    "_detect_hardcoded_paths_in_payload",
    "_detect_long_functions_in_payload",
    "_is_abstract_or_stub_body",
    "_path_is_print_exempt",
    "_payload_has_log_swallow",
    "_payload_has_print_call",
    "_step_introduces_async_without_await",
    "_step_introduces_hardcoded_path",
    "_step_introduces_log_swallow",
    "_step_introduces_long_function",
    "_step_introduces_print",
    # react_security_detectors (re-exported)
    "_detect_dynamic_exec_in_payload",
    "_detect_magic_numbers_in_payload",
    "_detect_repeated_literals_in_payload",
    "_detect_shell_injection_in_payload",
    "_detect_unsafe_deser_in_payload",
    "_payload_has_network_in_loop",
    "_step_introduces_dynamic_exec",
    "_step_introduces_magic_number",
    "_step_introduces_network_in_loop",
    "_step_introduces_repeated_literal",
    "_step_introduces_shell_injection",
    "_step_introduces_unsafe_deser",
]
