[General]
DisplayServer=x11
HaltCommand=/usr/bin/systemctl poweroff
RebootCommand=/usr/bin/systemctl reboot
GreeterEnvironment=QT_ACCESSIBILITY=1,ACCESSIBILITY_ENABLED=1,NO_AT_BRIDGE=0

[Theme]
Current=breeze

[Users]
MinimumUid=1000
MaximumUid=60000
HideUsers=sddm
HideShells=/usr/sbin/nologin,/bin/false
RememberLastUser=true
RememberLastSession=true

[X11]
ServerArguments=-nolisten tcp
SessionDir=/usr/share/xsessions
DisplayCommand=/usr/lib/echo-os/echo-sddm-xsetup
DisplayStopCommand=/usr/lib/echo-os/echo-sddm-xstop

[Wayland]
SessionDir=/usr/share/wayland-sessions
