[Include]
Include=mkosi-initrd

[Content]
Packages=
        systemd-cryptsetup
        cryptsetup-bin
        kmod
        util-linux
ExtraTrees=
        %D/mkosi.extra/etc/crypttab:/etc/crypttab
        %D/../../deploy/machine-state/echo-machine-id:/usr/lib/echo-os/echo-machine-id
        %D/mkosi.images/initrd/mkosi.extra/usr/lib/systemd/system/echo-machine-state-initrd.service:/usr/lib/systemd/system/echo-machine-state-initrd.service
        %D/mkosi.images/initrd/mkosi.extra/usr/lib/systemd/system/initrd-root-fs.target.d/echo-machine-state.conf:/usr/lib/systemd/system/initrd-root-fs.target.d/echo-machine-state.conf
