"""Find silent ``except: pass`` swallows that lack justification.

A silent swallow is acceptable only if:
  * The next line is a ``logger.debug`` / ``log.debug`` / similar
  * The except has a ``# noqa: BLE001`` or any inline comment
  * The except line carries an ``# intentional:`` / ``# best-effort``
    / ``# justified:`` marker

Anything else is flagged. This is **deliberately conservative** — a
single-line comment is enough to mute it. The goal isn't to remove
silent swallows, it's to make sure each one was thought about.

Baseline mode
-------------

Hundreds of pre-existing silent swallows shouldn't block adding the
audit. ``tools/lint/exception_audit_baseline.txt`` lists known sites
in ``path:line`` form; sites in the baseline are reported but don't
count as failures. New sites (anything not on that list) DO fail.

Whenever you add a justification comment to a baseline site, remove
its line from the baseline file. The audit refuses to start when a
baseline entry no longer matches a real swallow — that keeps the
list current.

Run::

    python tools/lint/exception_audit.py            # report new + baseline
    python tools/lint/exception_audit.py --strict   # exit 1 on NEW unjustified hits
    python tools/lint/exception_audit.py --write-baseline
                                                    # snapshot current state
                                                    # to baseline file
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
_BASELINE_PATH = REPO_ROOT / "tools" / "lint" / "exception_audit_baseline.txt"

# Files we deliberately exclude. all_skills is third-party-style scripts;
# tests don't need this discipline.
_EXCLUDE_PARTS: tuple[str, ...] = (
    "all_skills",
    "__pycache__",
    "tools/lint/fixtures",
)

# A silent swallow: ``except <anything>: ...`` immediately followed by
# ``pass`` (allowing for a comment in between).
_SWALLOW_RE = re.compile(
    r"""
    (?P<indent>[ \t]*)
    except\s+(?P<spec>[^\n:]*?)
    \s*:\s*
    (?P<except_comment>\#[^\n]*)?
    \n
    (?:[ \t]*\#[^\n]*\n)*
    [ \t]+pass\b
    """,
    re.VERBOSE | re.MULTILINE,
)

# Marker words that excuse a silent swallow.
_JUSTIFICATION_RE = re.compile(
    r"""
    (?:
        \#\s*noqa\b
      | \#\s*(?:justified|intentional|best[-_]effort|fall[-_]?through|hot[-_]path|expected)\b
    )
    """,
    re.IGNORECASE | re.VERBOSE,
)


def _is_justified(text: str, swallow_start: int, except_comment: str | None) -> bool:
    """Look for a justification on the except line, the line above, or
    the line below the ``pass``.
    """
    # Inline comment on the except itself
    if except_comment and _JUSTIFICATION_RE.search(except_comment):
        return True
    # Line above the except
    line_start = text.rfind("\n", 0, swallow_start) + 1
    prev_line_end = line_start - 1
    prev_line_start = text.rfind("\n", 0, prev_line_end - 1) + 1
    prev_line = text[prev_line_start:prev_line_end]
    return bool("#" in prev_line and _JUSTIFICATION_RE.search(prev_line))


def _load_baseline() -> set[str]:
    if not _BASELINE_PATH.is_file():
        return set()
    out: set[str] = set()
    for raw in _BASELINE_PATH.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        out.add(line)
    return out


def _write_baseline(hits: list[tuple[Path, int, str]]) -> None:
    lines = [
        "# Generated by tools/lint/exception_audit.py --write-baseline",
        "# Each line is `<path>:<line>` of an existing silent swallow.",
        "# When you justify a site (add a noqa or logger line), DELETE it",
        "# here. New silent swallows not on this list will fail strict mode.",
        "",
    ]
    for p, line, _ in sorted(hits, key=lambda x: (str(x[0]), x[1])):
        rel = p.relative_to(REPO_ROOT).as_posix()
        lines.append(f"{rel}:{line}")
    _BASELINE_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def audit(strict: bool = False) -> int:
    baseline = _load_baseline()
    hits: list[tuple[Path, int, str]] = []
    for p in (REPO_ROOT / "runtime").rglob("*.py"):
        rel_str = str(p).replace("\\", "/")
        if any(part in rel_str for part in _EXCLUDE_PARTS):
            continue
        try:
            text = p.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        for m in _SWALLOW_RE.finditer(text):
            if _is_justified(text, m.start(), m.group("except_comment")):
                continue
            line = text[: m.start()].count("\n") + 1
            spec = m.group("spec").strip()
            hits.append((p, line, spec))

    seen_keys = {f"{p.relative_to(REPO_ROOT).as_posix()}:{n}" for p, n, _ in hits}
    new_hits = [
        (p, n, s)
        for p, n, s in hits
        if f"{p.relative_to(REPO_ROOT).as_posix()}:{n}" not in baseline
    ]
    stale_baseline = baseline - seen_keys

    if not hits and not stale_baseline:
        print("OK · no unjustified silent except: pass in core runtime")
        return 0

    if stale_baseline:
        print(f"{len(stale_baseline)} baseline entries no longer match any swallow:")
        for entry in sorted(stale_baseline):
            print(f"  STALE  {entry}")
        print(
            "\nRemove the stale entries from "
            f"{_BASELINE_PATH.relative_to(REPO_ROOT).as_posix()} — they "
            "have been justified or the code has moved.",
        )

    if new_hits:
        print(f"\n{len(new_hits)} NEW unjustified silent swallow(s):")
        for p, line, spec in new_hits:
            rel = p.relative_to(REPO_ROOT).as_posix()
            print(f"  NEW    {rel}:{line}  except {spec}: pass")
        print(
            "\nFix one of:\n"
            "  1. Add a logger.debug(...) on the line after `pass`\n"
            "  2. Replace `pass` with a real handler\n"
            "  3. If swallowing is intentional, add a `# noqa: BLE001 — <why>` "
            "comment on the except line",
        )
    else:
        baseline_count = len(baseline & seen_keys)
        print(
            f"OK · {baseline_count} baseline silent swallow(s) still present (no new ones)",
        )

    if strict and (new_hits or stale_baseline):
        return 1
    return 0


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--strict",
        action="store_true",
        help="exit 1 if any NEW unjustified swallows or stale baseline entries are found",
    )
    p.add_argument(
        "--write-baseline",
        action="store_true",
        help="snapshot current state to the baseline file (run once after a sweep)",
    )
    args = p.parse_args()

    if args.write_baseline:
        hits: list[tuple[Path, int, str]] = []
        for path in (REPO_ROOT / "runtime").rglob("*.py"):
            rel_str = str(path).replace("\\", "/")
            if any(part in rel_str for part in _EXCLUDE_PARTS):
                continue
            try:
                text = path.read_text(encoding="utf-8")
            except (OSError, UnicodeDecodeError):
                continue
            for m in _SWALLOW_RE.finditer(text):
                if _is_justified(text, m.start(), m.group("except_comment")):
                    continue
                line = text[: m.start()].count("\n") + 1
                hits.append((path, line, m.group("spec").strip()))
        _write_baseline(hits)
        print(f"wrote {len(hits)} entries to {_BASELINE_PATH.relative_to(REPO_ROOT).as_posix()}")
        return 0

    return audit(strict=args.strict)


if __name__ == "__main__":
    sys.exit(main())
