"""mypy ratchet · gate NEW static-type errors without a big-bang cleanup.

The codebase has no full typing mandate, but an untyped 295k-line tree
means a whole class of bug has no net. This introduces mypy on the
highest-value packages incrementally: every error that exists TODAY is
frozen in ``tools/lint/mypy_baseline.txt``; the gate fails only on errors
NOT already in that baseline. So the type-error count can only go down.

Baseline keys are ``<path>\\t<code>\\t<message>`` — deliberately WITHOUT
line numbers, so an unrelated edit that shifts lines doesn't churn the
baseline or spuriously flag a moved-but-unchanged error. Duplicate errors
are tracked as a multiset (one baseline line each), so adding a second
identical error still trips the gate.

Usage::

    python tools/lint/mypy_ratchet.py              # gate: fail on new errors
    python tools/lint/mypy_ratchet.py --write-baseline   # freeze current set

Scope is ``_CHECK_PATHS`` (the hot packages); widen it as more of the tree
gets typed. mypy settings live in ``[tool.mypy]`` in pyproject.toml.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from collections import Counter
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
_BASELINE_PATH = REPO_ROOT / "tools" / "lint" / "mypy_baseline.txt"

# The packages under the ratchet. Widen as typing coverage grows — a
# newly-added path just contributes its current errors to the baseline.
_CHECK_PATHS: tuple[str, ...] = (
    "runtime/safety/auth",
    "runtime/core/cerebrum",
    "runtime/sensing/gateway",
    "runtime/platform/process",
    # Audit Q-04: doubled the covered surface (was 4 packages). The
    # ratchet freezes existing errors in mypy_baseline.txt; only NEW
    # errors fail.
    "runtime/safety/hooks",
    "runtime/platform/config",
    "runtime/core/nerves",
    "runtime/memory/journal",
)

# ``<path>:<line>: error: <message>  [<code>]`` — notes and summaries are
# ignored. Code is optional (a few mypy errors carry none).
_ERROR_RE = re.compile(r"^(?P<path>[^:]+):\d+: error: (?P<msg>.*?)(?:  \[(?P<code>[\w-]+)\])?$")


def _run_mypy() -> tuple[int, str]:
    proc = subprocess.run(
        [sys.executable, "-m", "mypy", *_CHECK_PATHS, "--no-error-summary", "--no-color-output"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
    )
    return proc.returncode, proc.stdout + proc.stderr


def _collect_errors(output: str) -> Counter[str]:
    """Parse mypy output into a multiset of line-independent error keys."""
    errors: Counter[str] = Counter()
    for line in output.splitlines():
        m = _ERROR_RE.match(line.rstrip())
        if not m:
            continue
        path = m.group("path").replace("\\", "/")
        code = m.group("code") or "?"
        msg = m.group("msg").strip()
        errors[f"{path}\t{code}\t{msg}"] += 1
    return errors


def _load_baseline() -> Counter[str]:
    baseline: Counter[str] = Counter()
    if not _BASELINE_PATH.is_file():
        return baseline
    for raw in _BASELINE_PATH.read_text(encoding="utf-8").splitlines():
        line = raw.rstrip("\n")
        if not line or line.startswith("#"):
            continue
        baseline[line] += 1
    return baseline


def _write_baseline(errors: Counter[str]) -> None:
    lines = [
        "# Generated by tools/lint/mypy_ratchet.py --write-baseline",
        "# Each line is `<path>\\t<code>\\t<message>` of an EXISTING mypy error",
        "# on the checked packages. New errors not on this list fail the gate.",
        "# Fixing an error? Re-run --write-baseline to ratchet the count down.",
    ]
    entries = sorted(errors.elements())
    if entries:
        lines.extend(["", *entries])
    _BASELINE_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _fmt(key: str) -> str:
    path, code, msg = key.split("\t", 2)
    return f"  {path}  [{code}] {msg}"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write-baseline",
        action="store_true",
        help="freeze the current mypy errors as the accepted baseline",
    )
    args = parser.parse_args()

    returncode, output = _run_mypy()
    current = _collect_errors(output)
    # mypy returns 1 both for normal type findings and for invocation failures
    # such as an unavailable module.  An unavailable checker must never look
    # like a clean empty result and silently disable the ratchet.
    if returncode not in {0, 1} or (returncode == 1 and not current):
        print("mypy invocation failed; type ratchet did not run:", file=sys.stderr)
        print(output.strip() or f"mypy exited with status {returncode}", file=sys.stderr)
        return 2

    if args.write_baseline:
        _write_baseline(current)
        total = sum(current.values())
        print(f"wrote {total} baseline error(s) to {_BASELINE_PATH.relative_to(REPO_ROOT)}")
        return 0

    baseline = _load_baseline()
    new = current - baseline  # multiset difference: only counts above baseline
    fixed = baseline - current  # in baseline but gone now — good, ratchet down

    if fixed:
        print(f"✓ {sum(fixed.values())} baseline error(s) fixed — run --write-baseline to lock in:")
        for key in sorted(set(fixed.elements()))[:10]:
            print(_fmt(key))
        if len(set(fixed.elements())) > 10:
            print(f"  … and {len(set(fixed.elements())) - 10} more")
        print()

    if new:
        print(f"✗ {sum(new.values())} NEW mypy error(s) on checked packages:")
        for key in sorted(new.elements()):
            print(_fmt(key))
        print(
            "\nFix them, or (if truly pre-existing) run "
            "`python tools/lint/mypy_ratchet.py --write-baseline`."
        )
        return 1

    print(
        f"OK · no new mypy errors ({sum(baseline.values())} baseline, {sum(current.values())} now)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
