#!/usr/bin/env python3
"""Audit A-04: generate the realtime protocol enums from Python.

The frontend used to hand-mirror ``runtime/protocol/items.py`` enums in
``frontend/src/core/realtime/items.ts`` and keep them in sync with a
regex-based parity test. Now the enums are GENERATED here into
``frontend/src/core/realtime/protocol-enums.generated.ts``; the parity
test is replaced by a no-diff check of this generator.

Usage::

    python scripts/gen_realtime_protocol_enums.py            # write
    python scripts/gen_realtime_protocol_enums.py --check    # fail on drift
"""

from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE = REPO_ROOT / "runtime" / "protocol" / "items.py"
OUTPUT = REPO_ROOT / "frontend" / "src" / "core" / "realtime" / "protocol-enums.generated.ts"

# (Python enum class name, TS export const name, TS type name)
_ENUMS: tuple[tuple[str, str, str], ...] = (
    ("ItemStatus", "ITEM_STATUSES", "ItemStatus"),
    ("TurnStatus", "TURN_STATUSES", "TurnStatus"),
    ("ItemType", "ITEM_TYPES", "ItemType"),
    ("ItemMarker", "ITEM_MARKERS", "ItemMarker"),
)


def _enum_members(tree: ast.Module, class_name: str) -> list[str]:
    for node in tree.body:
        if isinstance(node, ast.ClassDef) and node.name == class_name:
            out: list[str] = []
            for stmt in node.body:
                if isinstance(stmt, ast.Assign):
                    for target in stmt.targets:
                        if (
                            isinstance(target, ast.Name)
                            and isinstance(stmt.value, ast.Constant)
                            and isinstance(stmt.value.value, str)
                        ):
                            out.append(stmt.value.value)
                elif (
                    isinstance(stmt, ast.AnnAssign)
                    and isinstance(stmt.value, ast.Constant)
                    and isinstance(stmt.value.value, str)
                ):
                    out.append(stmt.value.value)
            return out
    raise SystemExit(f"enum class {class_name!r} not found in {SOURCE}")


def generate() -> str:
    tree = ast.parse(SOURCE.read_text(encoding="utf-8"))
    blocks: list[str] = [
        "// Generated by scripts/gen_realtime_protocol_enums.py (audit A-04).",
        "// DO NOT EDIT — source of truth is runtime/protocol/items.py.",
        "// Regenerate with: python scripts/gen_realtime_protocol_enums.py",
        "",
    ]
    for class_name, const_name, type_name in _ENUMS:
        values = _enum_members(tree, class_name)
        joined = ", ".join(f'"{v}"' for v in values)
        blocks.append(f"export const {const_name} = [{joined}] as const;")
        blocks.append(f"export type {type_name} = (typeof {const_name})[number];")
        blocks.append("")
    return "\n".join(blocks).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail when output is stale")
    args = ap.parse_args()

    rendered = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
            print(
                "protocol-enums.generated.ts is stale · run "
                "python scripts/gen_realtime_protocol_enums.py",
                file=sys.stderr,
            )
            return 1
        print("OK · realtime protocol enums are current")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())

