#!/usr/bin/env bash
# Audit A-08: scaffold a new persona agent with ZERO manual copy.
#
# Usage: scripts/new_persona_agent.sh <slug> ["Display Name"]
#
# Creates agents/<slug>/ with the standard layout every echo_* persona uses:
#   agent-core/{AGENTS,IDENTITY,MEMORY,USER,SOUL,BOOTSTRAP}.md
#   agent-core/tool-registry.jsonc
#   profile.jsonc  (template with slug/name filled in)
#   visuals/       (empty; drop in avatar/front/side/back images)
#
# The shared docs live in agents/_shared/ and are referenced, not copied —
# persona-specific files get a template header so the author fills them in.
set -u

slug="${1:-}"
name="${2:-}"
if [ -z "$slug" ]; then
  echo "usage: $0 <slug> [\"Display Name\"]" >&2
  exit 2
fi

repo_root="$(git rev-parse --show-toplevel 2>/dev/null || echo "$(cd "$(dirname "$0")/.." && pwd)")"
dest="$repo_root/agents/$slug"
if [ -e "$dest" ]; then
  echo "error: $dest already exists" >&2
  exit 1
fi

mkdir -p "$dest/agent-core" "$dest/visuals"

# Shared docs are referenced from agents/_shared/ (single source of truth);
# each persona gets its own IDENTITY/SOUL/MEMORY template to fill in.
for f in AGENTS BOOTSTRAP; do
  if [ -f "$repo_root/agents/_shared/$f.md" ]; then
    cp "$repo_root/agents/_shared/$f.md" "$dest/agent-core/$f.md"
  fi
done

for f in IDENTITY MEMORY USER SOUL; do
  cat > "$dest/agent-core/$f.md" <<MD
<!-- Generated by scripts/new_persona_agent.sh (audit A-08). Fill in:
     identity, memory, user-relationship, and soul for $slug. -->
# $f — $name
MD
done

cat > "$dest/agent-core/tool-registry.jsonc" <<'JSON'
{
  // Per-persona tool surface. Keep minimal; extend deliberately.
}
JSON

cat > "$dest/profile.jsonc" <<JSON
// ECHO Universe Echo agent profile — scaffolded by new_persona_agent.sh
{
  "id": "$slug",
  "templateId": "$slug",
  "templateVersion": "1.0.0",
  "name": "${name:-$slug}",
  "description": "",
  "icon": "E",
  "avatar": "avatar.png",
  "category": "creative",
  "tags": ["echo-universe", "character-agent"],
  "model": { "provider": "auto", "name": "auto" },
  "runtime": "local",
  "creator": "echo-universe-engine",
  "character_profile": {
    "id": "$slug",
    "name": "$name",
    "role": "",
    "theme": "",
    "status": "Alive",
    "quote": "",
    "abilities": [],
    "limitations": []
  },
  "capabilities": { "canon_review_required": true },
  "systemPrompt": {
    "includeMemoryMd": true,
    "includeUserMd": false,
    "includeAgentsMd": true,
    "includeBootstrapMd": true,
    "includeConstitution": true
  }
}
JSON

echo "scaffolded $dest (edit profile.jsonc + agent-core/*.md, add visuals/)"


