"""Versioned, plan-bound host migration for installed p3 appliances.

This is intentionally separate from the container image transaction. It owns
only additive Debian dependencies, a small allow-list of host systemd units,
and the Echo-owned Samba include required by native Time Machine.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import stat
import subprocess
import tempfile
from collections.abc import Callable
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

SCHEMA_VERSION = 1
MIGRATION_ID = "nas-maintenance-v4"
SOURCE_ROOT = Path("/opt/echo-os")
UNIT_DIRECTORY = Path("/etc/systemd/system")
MARKER_PATH = Path("/var/lib/echo-os/host-migration-nas-maintenance-v4.json")
DPKG_QUERY = Path("/usr/bin/dpkg-query")
APT_GET = Path("/usr/bin/apt-get")
SYSTEMCTL = Path("/usr/bin/systemctl")
TESTPARM = Path("/usr/bin/testparm")
SAMBA_CONFIG = Path("/etc/samba/smb.conf")
TIME_MACHINE_CONFIG = Path("/etc/samba/echo-os-time-machine.conf")
TIME_MACHINE_SOURCE = "deploy/provision/base/echo-os-time-machine.conf"
TIME_MACHINE_HEADER = b"# Generated by Echo OS. Manual edits are rejected and never merged.\n"
REMOTE_WRAPPER = Path("/usr/lib/echo-os/rclone-backup-mount")
REMOTE_WRAPPER_SOURCE = "deploy/appliance/rclone_backup_mount.py"
REMOTE_CREDENTIAL_DIRECTORY = Path("/etc/credstore.encrypted")
REMOTE_MOUNT_DIRECTORY = Path("/mnt/echo-backup-remotes")
MAX_UNIT_BYTES = 64 * 1024
PACKAGES = (
    "btrfs-progs",
    "fuse3",
    "hdparm",
    "nut-client",
    "nut-server",
    "rclone",
    "samba-vfs-modules",
    "smartmontools",
)
UNIT_SOURCES = {
    "echo-appliance.service": "deploy/provision/base/echo-appliance.service",
    "echo-ups-shutdown-guard.service": ("deploy/appliance/systemd/echo-ups-shutdown-guard.service"),
    "echo-ups-shutdown-guard.timer": ("deploy/appliance/systemd/echo-ups-shutdown-guard.timer"),
    "echo-smart-self-test.service": ("deploy/appliance/systemd/echo-smart-self-test.service"),
    "echo-smart-self-test.timer": ("deploy/appliance/systemd/echo-smart-self-test.timer"),
    "echo-mdraid-check.service": ("deploy/appliance/systemd/echo-mdraid-check.service"),
    "echo-mdraid-check.timer": ("deploy/appliance/systemd/echo-mdraid-check.timer"),
    "echo-btrfs-scrub.service": ("deploy/appliance/systemd/echo-btrfs-scrub.service"),
    "echo-btrfs-scrub.timer": ("deploy/appliance/systemd/echo-btrfs-scrub.timer"),
    "echo-btrfs-snapshot.service": ("deploy/appliance/systemd/echo-btrfs-snapshot.service"),
    "echo-btrfs-snapshot.timer": ("deploy/appliance/systemd/echo-btrfs-snapshot.timer"),
    "echo-disk-idle.service": ("deploy/appliance/systemd/echo-disk-idle.service"),
    "echo-rclone-backup@.service": (
        "deploy/appliance/systemd/echo-rclone-backup@.service"
    ),
}
TIMERS = (
    "echo-ups-shutdown-guard.timer",
    "echo-smart-self-test.timer",
    "echo-mdraid-check.timer",
    "echo-btrfs-scrub.timer",
    "echo-btrfs-snapshot.timer",
)
SERVICES = ("echo-disk-idle.service",)
ENABLED_UNITS = (*TIMERS, *SERVICES)


class HostMigrationError(RuntimeError):
    """The host migration could not be planned or applied safely."""


def _sha256(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def _canonical(value: Any) -> bytes:
    return json.dumps(value, sort_keys=True, separators=(",", ":")).encode("utf-8")


def _safe_directory(path: Path, *, trusted_uid: int) -> None:
    try:
        metadata = path.lstat()
    except OSError as exc:
        raise HostMigrationError(f"required directory is unavailable: {path}") from exc
    if not stat.S_ISDIR(metadata.st_mode) or stat.S_ISLNK(metadata.st_mode):
        raise HostMigrationError(f"unsafe directory: {path}")
    if metadata.st_uid != trusted_uid or (os.name == "posix" and metadata.st_mode & 0o022):
        raise HostMigrationError(f"unsafe directory ownership or mode: {path}")


def _source_payloads(source_root: Path, *, trusted_uid: int) -> dict[str, bytes]:
    _safe_directory(source_root, trusted_uid=trusted_uid)
    resolved_root = source_root.resolve(strict=True)
    result: dict[str, bytes] = {}
    for unit, relative in UNIT_SOURCES.items():
        path = source_root / relative
        try:
            metadata = path.lstat()
            resolved = path.resolve(strict=True)
        except OSError as exc:
            raise HostMigrationError(f"migration source is missing: {relative}") from exc
        if (
            not stat.S_ISREG(metadata.st_mode)
            or stat.S_ISLNK(metadata.st_mode)
            or not resolved.is_relative_to(resolved_root)
            or metadata.st_uid != trusted_uid
            or (os.name == "posix" and metadata.st_mode & 0o022)
            or metadata.st_size > MAX_UNIT_BYTES
        ):
            raise HostMigrationError(f"unsafe migration source: {relative}")
        payload = path.read_bytes()
        if len(payload) > MAX_UNIT_BYTES or not payload.endswith(b"\n"):
            raise HostMigrationError(f"invalid migration unit: {relative}")
        result[unit] = payload
    return result


def _source_file(
    source_root: Path, relative: str, *, trusted_uid: int, label: str
) -> bytes:
    _safe_directory(source_root, trusted_uid=trusted_uid)
    resolved_root = source_root.resolve(strict=True)
    path = source_root / relative
    try:
        metadata = path.lstat()
        resolved = path.resolve(strict=True)
    except OSError as exc:
        raise HostMigrationError(f"migration source is missing: {relative}") from exc
    if (
        not stat.S_ISREG(metadata.st_mode)
        or stat.S_ISLNK(metadata.st_mode)
        or not resolved.is_relative_to(resolved_root)
        or metadata.st_uid != trusted_uid
        or (os.name == "posix" and metadata.st_mode & 0o022)
        or metadata.st_size > MAX_UNIT_BYTES
    ):
        raise HostMigrationError(f"unsafe migration source: {relative}")
    payload = path.read_bytes()
    if len(payload) > MAX_UNIT_BYTES or not payload.endswith(b"\n"):
        raise HostMigrationError(f"invalid migration {label}: {relative}")
    return payload


def _samba_include_state(payload: bytes, managed_path: Path) -> str:
    try:
        text = payload.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise HostMigrationError("Samba configuration is not UTF-8") from exc
    expected = str(managed_path)
    section = ""
    matches = 0
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith(("#", ";")):
            continue
        if line.startswith("[") and line.endswith("]"):
            section = line[1:-1].strip().casefold()
            continue
        key, separator, value = line.partition("=")
        if separator and key.strip().casefold() == "include" and value.strip() == expected:
            if section != "global":
                raise HostMigrationError("Echo Time Machine include is outside Samba global section")
            matches += 1
    if matches > 1:
        raise HostMigrationError("Echo Time Machine include is duplicated")
    return "present" if matches == 1 else "add"


def _insert_samba_include(payload: bytes, managed_path: Path) -> bytes:
    if _samba_include_state(payload, managed_path) == "present":
        return payload
    text = payload.decode("utf-8")
    lines = text.splitlines(keepends=True)
    for index, line in enumerate(lines):
        if line.strip().casefold() == "[global]":
            newline = "\r\n" if line.endswith("\r\n") else "\n"
            lines.insert(index + 1, f"include = {managed_path}{newline}")
            return "".join(lines).encode("utf-8")
    raise HostMigrationError("Samba configuration has no global section")


def _target_payload(path: Path, *, trusted_uid: int) -> bytes | None:
    try:
        metadata = path.lstat()
    except FileNotFoundError:
        return None
    if (
        not stat.S_ISREG(metadata.st_mode)
        or stat.S_ISLNK(metadata.st_mode)
        or metadata.st_uid != trusted_uid
        or (os.name == "posix" and metadata.st_mode & 0o022)
        or metadata.st_size > MAX_UNIT_BYTES
    ):
        raise HostMigrationError(f"unsafe installed unit: {path.name}")
    payload = path.read_bytes()
    if len(payload) > MAX_UNIT_BYTES:
        raise HostMigrationError(f"installed unit grew beyond its safety limit: {path.name}")
    return payload


def _managed_directory_operation(
    path: Path, *, trusted_uid: int, exact_mode: int | None = None
) -> str:
    if path.exists() or path.is_symlink():
        _safe_directory(path, trusted_uid=trusted_uid)
        if (
            os.name == "posix"
            and exact_mode is not None
            and stat.S_IMODE(path.stat().st_mode) != exact_mode
        ):
            return "chmod"
        return "none"
    _safe_directory(path.parent, trusted_uid=trusted_uid)
    return "create"


def _migration_evidence_current(path: Path, *, trusted_uid: int) -> bool:
    try:
        metadata = path.lstat()
    except FileNotFoundError:
        return False
    if (
        not stat.S_ISREG(metadata.st_mode)
        or stat.S_ISLNK(metadata.st_mode)
        or metadata.st_uid != trusted_uid
        or (os.name == "posix" and metadata.st_mode & 0o022)
        or metadata.st_size > MAX_UNIT_BYTES
    ):
        raise HostMigrationError(f"unsafe migration evidence: {path}")
    payload = path.read_bytes()
    if len(payload) > MAX_UNIT_BYTES:
        raise HostMigrationError("migration evidence grew beyond its safety limit")
    try:
        evidence = json.loads(payload)
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise HostMigrationError("migration evidence is invalid") from exc
    return (
        isinstance(evidence, dict)
        and type(evidence.get("schemaVersion")) is int
        and evidence["schemaVersion"] == SCHEMA_VERSION
        and evidence.get("migrationId") == MIGRATION_ID
    )


def _run(
    executable: Path,
    arguments: tuple[str, ...],
    *,
    runner: Callable[..., subprocess.CompletedProcess[str]],
    timeout: float,
) -> subprocess.CompletedProcess[str]:
    if not executable.is_file() or executable.is_symlink():
        raise HostMigrationError(f"trusted executable is unavailable: {executable.name}")
    try:
        return runner(
            [str(executable), *arguments],
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=timeout,
            check=False,
            env={**os.environ, "LC_ALL": "C"},
        )
    except (OSError, subprocess.SubprocessError) as exc:
        raise HostMigrationError(f"host command failed: {executable.name}") from exc


def package_installed(
    package: str,
    *,
    runner: Callable[..., subprocess.CompletedProcess[str]] = subprocess.run,
    dpkg_query: Path = DPKG_QUERY,
) -> bool:
    if package not in PACKAGES:
        raise HostMigrationError("package probe escaped the migration allow-list")
    completed = _run(
        dpkg_query,
        ("-W", "-f=${db:Status-Status}", package),
        runner=runner,
        timeout=15.0,
    )
    return completed.returncode == 0 and completed.stdout.strip() == "installed"


def unit_enabled(
    unit: str,
    *,
    runner: Callable[..., subprocess.CompletedProcess[str]] = subprocess.run,
    systemctl: Path = SYSTEMCTL,
) -> bool:
    if unit not in ENABLED_UNITS:
        raise HostMigrationError("unit probe escaped the migration allow-list")
    completed = _run(
        systemctl,
        ("is-enabled", "--quiet", unit),
        runner=runner,
        timeout=15.0,
    )
    return completed.returncode == 0


def appliance_active(
    *,
    runner: Callable[..., subprocess.CompletedProcess[str]] = subprocess.run,
    systemctl: Path = SYSTEMCTL,
) -> bool:
    completed = _run(
        systemctl,
        ("is-active", "--quiet", "echo-appliance.service"),
        runner=runner,
        timeout=15.0,
    )
    return completed.returncode == 0


def plan_migration(
    *,
    source_root: Path = SOURCE_ROOT,
    unit_directory: Path = UNIT_DIRECTORY,
    marker_path: Path = MARKER_PATH,
    samba_config_path: Path = SAMBA_CONFIG,
    time_machine_config_path: Path = TIME_MACHINE_CONFIG,
    remote_wrapper_path: Path = REMOTE_WRAPPER,
    remote_credential_directory: Path = REMOTE_CREDENTIAL_DIRECTORY,
    remote_mount_directory: Path = REMOTE_MOUNT_DIRECTORY,
    trusted_uid: int = 0,
    package_probe: Callable[[str], bool] = package_installed,
    enabled_probe: Callable[[str], bool] = unit_enabled,
) -> dict[str, Any]:
    sources = _source_payloads(source_root, trusted_uid=trusted_uid)
    time_machine_source = _source_file(
        source_root,
        TIME_MACHINE_SOURCE,
        trusted_uid=trusted_uid,
        label="Time Machine configuration",
    )
    remote_wrapper_source = _source_file(
        source_root,
        REMOTE_WRAPPER_SOURCE,
        trusted_uid=trusted_uid,
        label="rclone backup mount wrapper",
    )
    _safe_directory(unit_directory, trusted_uid=trusted_uid)
    _safe_directory(marker_path.parent, trusted_uid=trusted_uid)
    _safe_directory(samba_config_path.parent, trusted_uid=trusted_uid)
    if time_machine_config_path.parent != samba_config_path.parent:
        _safe_directory(time_machine_config_path.parent, trusted_uid=trusted_uid)
    _safe_directory(remote_wrapper_path.parent, trusted_uid=trusted_uid)
    remote_wrapper_installed = _target_payload(remote_wrapper_path, trusted_uid=trusted_uid)
    managed_directories = {
        str(remote_credential_directory): _managed_directory_operation(
            remote_credential_directory, trusted_uid=trusted_uid, exact_mode=0o700
        ),
        str(remote_mount_directory): _managed_directory_operation(
            remote_mount_directory, trusted_uid=trusted_uid
        ),
    }
    evidence_current = _migration_evidence_current(marker_path, trusted_uid=trusted_uid)
    units: list[dict[str, Any]] = []
    for name, source in sources.items():
        installed = _target_payload(unit_directory / name, trusted_uid=trusted_uid)
        units.append(
            {
                "name": name,
                "sourceSha256": _sha256(source),
                "installedSha256": _sha256(installed) if installed is not None else None,
                "operation": "none" if installed == source else "install",
            }
        )
    missing_packages = [package for package in PACKAGES if not package_probe(package)]
    samba_config = _target_payload(samba_config_path, trusted_uid=trusted_uid)
    if samba_config is None:
        raise HostMigrationError("Samba configuration is missing")
    include_operation = _samba_include_state(samba_config, time_machine_config_path)
    installed_time_machine = _target_payload(time_machine_config_path, trusted_uid=trusted_uid)
    if installed_time_machine is not None and not installed_time_machine.startswith(
        TIME_MACHINE_HEADER
    ):
        raise HostMigrationError("existing Time Machine configuration is not Echo-managed")
    time_machine_operation = "install" if installed_time_machine is None else "none"
    enable_timers = [timer for timer in TIMERS if not enabled_probe(timer)]
    enable_services = [service for service in SERVICES if not enabled_probe(service)]
    operation = (
        "none"
        if not missing_packages
        and include_operation == "present"
        and time_machine_operation == "none"
        and remote_wrapper_installed == remote_wrapper_source
        and all(value == "none" for value in managed_directories.values())
        and not enable_timers
        and not enable_services
        and evidence_current
        and all(item["operation"] == "none" for item in units)
        else "migrate"
    )
    binding = {
        "schemaVersion": SCHEMA_VERSION,
        "migrationId": MIGRATION_ID,
        "operation": operation,
        "packages": {
            "missing": missing_packages,
            "policy": "additiveOnlyNoAutomaticRemoval",
        },
        "units": units,
        "timeMachine": {
            "sourceSha256": _sha256(time_machine_source),
            "installedSha256": (
                _sha256(installed_time_machine) if installed_time_machine is not None else None
            ),
            "configOperation": time_machine_operation,
            "sambaConfigSha256": _sha256(samba_config),
            "includeOperation": include_operation,
        },
        "remoteMount": {
            "wrapperSourceSha256": _sha256(remote_wrapper_source),
            "wrapperInstalledSha256": (
                _sha256(remote_wrapper_installed)
                if remote_wrapper_installed is not None
                else None
            ),
            "wrapperOperation": (
                "none" if remote_wrapper_installed == remote_wrapper_source else "install"
            ),
            "directories": managed_directories,
        },
        "enableTimers": enable_timers,
        "enableServices": enable_services,
        "restartServices": ["echo-appliance.service"],
        "evidenceCurrent": evidence_current,
        "scope": "p3BareMetalHost",
    }
    return {
        **binding,
        "planId": _sha256(_canonical(binding)),
        "requiresRoot": True,
        "rollback": {
            "units": "restoredOnFailure",
            "samba": "configAndIncludeRestoredOnFailure",
            "remoteMount": "wrapperRestoredAndNewEmptyDirectoriesRemovedOnFailure",
            "newPackages": "retained",
            "data": "untouched",
        },
    }


def _atomic_write(
    path: Path,
    payload: bytes,
    *,
    trusted_uid: int,
    trusted_gid: int,
    mode: int = 0o644,
) -> None:
    descriptor, temporary_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "wb") as handle:
            handle.write(payload)
            handle.flush()
            os.fsync(handle.fileno())
        os.chmod(temporary, mode)
        if os.name == "posix":
            os.chown(temporary, trusted_uid, trusted_gid)
        os.replace(temporary, path)
        if os.name == "posix":
            directory = os.open(path.parent, os.O_RDONLY | getattr(os, "O_DIRECTORY", 0))
            try:
                os.fsync(directory)
            finally:
                os.close(directory)
    finally:
        temporary.unlink(missing_ok=True)


def _systemctl(
    *arguments: str,
    runner: Callable[..., subprocess.CompletedProcess[str]],
    systemctl: Path,
) -> None:
    completed = _run(systemctl, tuple(arguments), runner=runner, timeout=45.0)
    if completed.returncode != 0:
        raise HostMigrationError(f"systemd rejected operation: {' '.join(arguments)}")


def apply_migration(
    plan_id: str,
    *,
    source_root: Path = SOURCE_ROOT,
    unit_directory: Path = UNIT_DIRECTORY,
    marker_path: Path = MARKER_PATH,
    samba_config_path: Path = SAMBA_CONFIG,
    time_machine_config_path: Path = TIME_MACHINE_CONFIG,
    remote_wrapper_path: Path = REMOTE_WRAPPER,
    remote_credential_directory: Path = REMOTE_CREDENTIAL_DIRECTORY,
    remote_mount_directory: Path = REMOTE_MOUNT_DIRECTORY,
    trusted_uid: int = 0,
    trusted_gid: int = 0,
    package_probe: Callable[[str], bool] = package_installed,
    enabled_probe: Callable[[str], bool] = unit_enabled,
    active_probe: Callable[[], bool] = appliance_active,
    runner: Callable[..., subprocess.CompletedProcess[str]] = subprocess.run,
    apt_get: Path = APT_GET,
    systemctl: Path = SYSTEMCTL,
    testparm: Path = TESTPARM,
    clock: Callable[[], datetime] = lambda: datetime.now(UTC),
) -> dict[str, Any]:
    if os.name == "posix" and os.geteuid() != trusted_uid:
        raise HostMigrationError("host migration requires root")
    plan = plan_migration(
        source_root=source_root,
        unit_directory=unit_directory,
        marker_path=marker_path,
        samba_config_path=samba_config_path,
        time_machine_config_path=time_machine_config_path,
        remote_wrapper_path=remote_wrapper_path,
        remote_credential_directory=remote_credential_directory,
        remote_mount_directory=remote_mount_directory,
        trusted_uid=trusted_uid,
        package_probe=package_probe,
        enabled_probe=enabled_probe,
    )
    if plan["planId"] != plan_id:
        raise HostMigrationError("host migration plan is stale; preview again")
    if plan["operation"] == "none":
        if not active_probe():
            raise HostMigrationError("appliance service is not active")
        return {**plan, "applied": False, "verified": True}

    missing_packages = tuple(plan["packages"]["missing"])
    if missing_packages:
        if _run(apt_get, ("update",), runner=runner, timeout=300.0).returncode != 0:
            raise HostMigrationError("apt metadata refresh failed")
        install = _run(
            apt_get,
            ("install", "--yes", "--no-install-recommends", *missing_packages),
            runner=runner,
            timeout=900.0,
        )
        if install.returncode != 0 or any(not package_probe(item) for item in missing_packages):
            raise HostMigrationError("required host package installation failed")

    sources = _source_payloads(source_root, trusted_uid=trusted_uid)
    time_machine_source = _source_file(
        source_root,
        TIME_MACHINE_SOURCE,
        trusted_uid=trusted_uid,
        label="Time Machine configuration",
    )
    remote_wrapper_source = _source_file(
        source_root,
        REMOTE_WRAPPER_SOURCE,
        trusted_uid=trusted_uid,
        label="rclone backup mount wrapper",
    )
    originals = {
        name: _target_payload(unit_directory / name, trusted_uid=trusted_uid) for name in sources
    }
    original_samba = _target_payload(samba_config_path, trusted_uid=trusted_uid)
    original_time_machine = _target_payload(
        time_machine_config_path, trusted_uid=trusted_uid
    )
    original_remote_wrapper = _target_payload(
        remote_wrapper_path, trusted_uid=trusted_uid
    )
    original_remote_wrapper_mode = (
        remote_wrapper_path.stat().st_mode & 0o777
        if original_remote_wrapper is not None
        else None
    )
    assert original_samba is not None
    planned_units = {item["name"]: item for item in plan["units"]}
    if any(
        _sha256(payload) != planned_units[name]["sourceSha256"]
        or (_sha256(originals[name]) if originals[name] is not None else None)
        != planned_units[name]["installedSha256"]
        for name, payload in sources.items()
    ):
        raise HostMigrationError(
            "host migration source or installed units changed after package installation"
        )
    planned_time_machine = plan["timeMachine"]
    if (
        _sha256(time_machine_source) != planned_time_machine["sourceSha256"]
        or _sha256(original_samba) != planned_time_machine["sambaConfigSha256"]
        or (
            _sha256(original_time_machine) if original_time_machine is not None else None
        )
        != planned_time_machine["installedSha256"]
    ):
        raise HostMigrationError(
            "host migration source or Samba configuration changed after package installation"
        )
    planned_remote = plan["remoteMount"]
    if (
        _sha256(remote_wrapper_source) != planned_remote["wrapperSourceSha256"]
        or (
            _sha256(original_remote_wrapper)
            if original_remote_wrapper is not None
            else None
        )
        != planned_remote["wrapperInstalledSha256"]
        or {
            str(remote_credential_directory): _managed_directory_operation(
                remote_credential_directory, trusted_uid=trusted_uid, exact_mode=0o700
            ),
            str(remote_mount_directory): _managed_directory_operation(
                remote_mount_directory, trusted_uid=trusted_uid
            ),
        }
        != planned_remote["directories"]
    ):
        raise HostMigrationError(
            "host migration remote mount assets changed after package installation"
        )
    previously_enabled = {unit: enabled_probe(unit) for unit in ENABLED_UNITS}
    changed: list[str] = []
    marker = {
        "schemaVersion": SCHEMA_VERSION,
        "migrationId": MIGRATION_ID,
        "planId": plan_id,
        "appliedAt": clock().astimezone(UTC).isoformat(timespec="seconds").replace("+00:00", "Z"),
        "packagesInstalled": list(missing_packages),
        "unitSha256": {name: _sha256(payload) for name, payload in sources.items()},
        "timeMachineConfigSha256": _sha256(
            original_time_machine
            if original_time_machine is not None
            else time_machine_source
        ),
        "remoteWrapperSha256": _sha256(remote_wrapper_source),
        "enabledTimers": list(TIMERS),
        "enabledServices": list(SERVICES),
    }
    samba_changed = False
    time_machine_changed = False
    remote_wrapper_changed = False
    created_directories: list[Path] = []
    original_directory_modes: dict[Path, int] = {}
    try:
        for path in (remote_credential_directory, remote_mount_directory):
            wanted_mode = 0o700 if path == remote_credential_directory else 0o755
            if not path.exists():
                path.mkdir(mode=wanted_mode)
                if os.name == "posix":
                    os.chown(path, trusted_uid, trusted_gid)
                created_directories.append(path)
            elif os.name == "posix":
                original_directory_modes[path] = stat.S_IMODE(path.stat().st_mode)
                os.chmod(path, wanted_mode)
            _safe_directory(path, trusted_uid=trusted_uid)
        if original_remote_wrapper != remote_wrapper_source:
            _atomic_write(
                remote_wrapper_path,
                remote_wrapper_source,
                trusted_uid=trusted_uid,
                trusted_gid=trusted_gid,
                mode=0o755,
            )
            remote_wrapper_changed = True
        if original_time_machine is None:
            _atomic_write(
                time_machine_config_path,
                time_machine_source,
                trusted_uid=trusted_uid,
                trusted_gid=trusted_gid,
            )
            time_machine_changed = True
        wanted_samba = _insert_samba_include(original_samba, time_machine_config_path)
        if wanted_samba != original_samba:
            _atomic_write(
                samba_config_path,
                wanted_samba,
                trusted_uid=trusted_uid,
                trusted_gid=trusted_gid,
            )
            samba_changed = True
        check = _run(
            testparm,
            ("-s", str(samba_config_path)),
            runner=runner,
            timeout=30.0,
        )
        if check.returncode != 0:
            raise HostMigrationError("Samba rejected the Time Machine include")
        _systemctl("reload", "smbd.service", runner=runner, systemctl=systemctl)
        for name, payload in sources.items():
            if originals[name] != payload:
                changed.append(name)
                _atomic_write(
                    unit_directory / name,
                    payload,
                    trusted_uid=trusted_uid,
                    trusted_gid=trusted_gid,
                )
        _systemctl("daemon-reload", runner=runner, systemctl=systemctl)
        for timer in plan["enableTimers"]:
            _systemctl("enable", "--now", timer, runner=runner, systemctl=systemctl)
        for service in plan["enableServices"]:
            _systemctl("enable", "--now", service, runner=runner, systemctl=systemctl)
        _systemctl("restart", "echo-appliance.service", runner=runner, systemctl=systemctl)
        installed_time_machine = _target_payload(
            time_machine_config_path, trusted_uid=trusted_uid
        )
        installed_samba = _target_payload(samba_config_path, trusted_uid=trusted_uid)
        if (
            installed_time_machine is None
            or not installed_time_machine.startswith(TIME_MACHINE_HEADER)
            or installed_samba is None
            or _samba_include_state(installed_samba, time_machine_config_path) != "present"
        ):
            raise HostMigrationError("Time Machine host configuration verification failed")
        for name, payload in sources.items():
            if _target_payload(unit_directory / name, trusted_uid=trusted_uid) != payload:
                raise HostMigrationError(f"installed unit verification failed: {name}")
        if (
            _target_payload(remote_wrapper_path, trusted_uid=trusted_uid)
            != remote_wrapper_source
            or (
                os.name == "posix"
                and (remote_wrapper_path.stat().st_mode & 0o777) != 0o755
            )
        ):
            raise HostMigrationError("rclone backup mount wrapper verification failed")
        for path in (remote_credential_directory, remote_mount_directory):
            _safe_directory(path, trusted_uid=trusted_uid)
        if (
            os.name == "posix"
            and stat.S_IMODE(remote_credential_directory.stat().st_mode) != 0o700
        ):
            raise HostMigrationError("encrypted credential directory mode is invalid")
        if any(not enabled_probe(timer) for timer in TIMERS):
            raise HostMigrationError("timer enablement verification failed")
        if any(not enabled_probe(service) for service in SERVICES):
            raise HostMigrationError("service enablement verification failed")
        if not active_probe():
            raise HostMigrationError("appliance service did not become active")
        _atomic_write(
            marker_path,
            _canonical(marker) + b"\n",
            trusted_uid=trusted_uid,
            trusted_gid=trusted_gid,
        )
    except (OSError, HostMigrationError) as exc:
        rollback_errors: list[str] = []
        if remote_wrapper_changed:
            try:
                if original_remote_wrapper is None:
                    if remote_wrapper_path.is_symlink():
                        raise OSError("refusing to unlink a replaced wrapper symlink")
                    remote_wrapper_path.unlink(missing_ok=True)
                else:
                    _atomic_write(
                        remote_wrapper_path,
                        original_remote_wrapper,
                        trusted_uid=trusted_uid,
                        trusted_gid=trusted_gid,
                        mode=original_remote_wrapper_mode or 0o755,
                    )
            except OSError:
                rollback_errors.append("rclone-backup-mount")
        for name in reversed(changed):
            target = unit_directory / name
            try:
                original = originals[name]
                if original is None:
                    if target.is_symlink():
                        raise OSError("refusing to unlink a replaced unit symlink")
                    if target.exists():
                        target.unlink()
                else:
                    _atomic_write(
                        target,
                        original,
                        trusted_uid=trusted_uid,
                        trusted_gid=trusted_gid,
                    )
            except OSError:
                rollback_errors.append(name)
        if samba_changed:
            try:
                _atomic_write(
                    samba_config_path,
                    original_samba,
                    trusted_uid=trusted_uid,
                    trusted_gid=trusted_gid,
                )
            except OSError:
                rollback_errors.append("smb.conf")
        if time_machine_changed:
            try:
                if time_machine_config_path.is_symlink():
                    raise OSError("refusing to unlink a replaced Time Machine config symlink")
                if time_machine_config_path.exists():
                    time_machine_config_path.unlink()
            except OSError:
                rollback_errors.append("time-machine-config")
        for path in reversed(created_directories):
            try:
                path.rmdir()
            except OSError:
                rollback_errors.append(str(path))
        for path, mode in original_directory_modes.items():
            try:
                os.chmod(path, mode)
            except OSError:
                rollback_errors.append(f"mode:{path}")
        try:
            _systemctl("daemon-reload", runner=runner, systemctl=systemctl)
            for unit, was_enabled in previously_enabled.items():
                if not was_enabled:
                    _systemctl("disable", "--now", unit, runner=runner, systemctl=systemctl)
            if samba_changed or time_machine_changed:
                _systemctl("reload", "smbd.service", runner=runner, systemctl=systemctl)
            _systemctl("restart", "echo-appliance.service", runner=runner, systemctl=systemctl)
        except HostMigrationError:
            rollback_errors.append("systemd")
        if rollback_errors:
            raise HostMigrationError(
                f"host migration failed ({exc}) and rollback was incomplete: "
                + ", ".join(rollback_errors)
            ) from exc
        raise HostMigrationError(
            f"host migration failed ({exc}); units and Samba configuration were restored "
            "and newly installed packages were retained"
        ) from exc

    return {
        **plan,
        "applied": True,
        "verified": True,
        "marker": str(marker_path),
        "packagesInstalled": list(missing_packages),
        "unitsInstalled": changed,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    action = parser.add_mutually_exclusive_group(required=True)
    action.add_argument("--plan", action="store_true")
    action.add_argument("--apply", metavar="PLAN_ID")
    arguments = parser.parse_args(argv)
    try:
        result = plan_migration() if arguments.plan else apply_migration(arguments.apply)
    except HostMigrationError as exc:
        print(f"host migration refused: {exc}", file=os.sys.stderr)
        return 2
    print(json.dumps(result, ensure_ascii=False, sort_keys=True, separators=(",", ":")))
    return 0


if __name__ == "__main__":  # pragma: no cover - CLI boundary
    raise SystemExit(main())
