"""Collaboration / wiki / tentacle / terminal / channel router wiring.

Extracted from ``app.py`` during the god-file reduction (§2.5 of the
navigation map). Mounts auto-wiki, local-brain setup, team
role-model tiering, the mobile tentacle bridge (WebSocket), semantic
retrieval, persistent terminal, and IM channels routers.
"""

from __future__ import annotations

import logging
from typing import Any

from ._app_context import AppContext


def mount_collaboration(
    ctx: AppContext,
    *,
    channel_manager: Any,
    tentacle_enabled: bool,
    tentacle_ws_port: int,
) -> None:
    """Mount the collaboration-surface routers onto ctx.app."""
    app = ctx.app
    stack = ctx.stack

    # ─── Auto wiki · serves docs/auto/ tree to the Wiki tab ───
    # Generated by ``scripts/gen_wiki.py`` · the router only reads
    # and optionally triggers regeneration · no LLM involved.
    from runtime.sensing.gateway.wiki_router import create_wiki_router

    _wiki_planner = getattr(stack, "planner", None) if stack is not None else None
    app.include_router(
        create_wiki_router(
            model_router=getattr(_wiki_planner, "router", None),
            model=getattr(_wiki_planner, "planner_model", None),
            identity_store=ctx.identity_store,
            require_auth=ctx.require_auth,
            jwt_secret=ctx.jwt_secret,
            jwt_issuer=ctx.jwt_issuer,
            jwt_audience=ctx.jwt_audience,
        )
    )

    # Local-brain setup wizard · plain-language readiness checklist so a
    # non-technical user can wire the whole stack to run locally.
    from runtime.sensing.gateway.local_brain_router import create_local_brain_router

    app.include_router(
        create_local_brain_router(
            identity_store=ctx.identity_store,
            require_auth=ctx.require_auth,
            jwt_secret=ctx.jwt_secret,
            jwt_issuer=ctx.jwt_issuer,
            jwt_audience=ctx.jwt_audience,
        )
    )

    # Same-origin Storage gateway.  Browsers use /api/storage/v1/* on the
    # agent; the private 8767 service and its bearer token remain server-side.
    from runtime.sensing.gateway.storage_proxy_router import create_storage_proxy_router

    app.include_router(
        create_storage_proxy_router(
            identity_store=ctx.identity_store,
            require_auth=ctx.require_auth,
            jwt_secret=ctx.jwt_secret,
            jwt_issuer=ctx.jwt_issuer,
            jwt_audience=ctx.jwt_audience,
        )
    )

    # Team role-model tiering · per-role cheap/primary override (cost control).
    from runtime.sensing.gateway.team_role_models_router import (
        create_team_role_models_router,
    )

    app.include_router(
        create_team_role_models_router(
            identity_store=ctx.identity_store,
            require_auth=ctx.require_auth,
            jwt_secret=ctx.jwt_secret,
            jwt_issuer=ctx.jwt_issuer,
            jwt_audience=ctx.jwt_audience,
        )
    )

    # Mobile (tentacle) · phones running echo-mobile connect over WebSocket
    # via the existing tentacle bridge and appear in the team. Mount the device
    # dashboard router (/api/tentacle/*) into the main app and start the WS
    # server in this app's event loop, so the team reads live device state in
    # one process. Deterministic e2e configs can disable this bridge to avoid
    # binding a fixed LAN port unrelated to the web gateway.
    if tentacle_enabled:
        try:
            _tentacle_ws_port = int(tentacle_ws_port)
            if not (1 <= _tentacle_ws_port <= 65535):
                raise ValueError("tentacle_ws_port must be between 1 and 65535")
        except (TypeError, ValueError):
            logging.getLogger(__name__).warning(
                "invalid tentacle_ws_port=%r; falling back to 8765",
                tentacle_ws_port,
            )
            _tentacle_ws_port = 8765

        try:
            from runtime.core.cerebrum.planner import StaticPlanner
            from runtime.sensing.gateway.tentacle_join_router import (
                create_tentacle_join_router,
            )
            from runtime.tentacle.coordinator import TentacleCoordinator
            from runtime.tentacle.dashboard import create_tentacle_router
            from runtime.tentacle.mobile.cerebrum_adapter import CerebrumDecisionAdapter
            from runtime.tentacle.team_bridge import (
                get_or_create_tentacle_token,
                set_active_coordinator,
            )

            # Shared secret a LAN phone presents to join (loopback joins tokenless).
            _tentacle_token = get_or_create_tentacle_token()

            # Reuse the stack's planner when it can plan; else a bare StaticPlanner
            # (the adapter degrades gracefully — a failed/empty plan just yields no
            # device actions rather than crashing). This is the decision engine that
            # turns a team task's natural-language goal into device tool calls.
            _tentacle_planner = getattr(stack, "planner", None)
            if not callable(getattr(_tentacle_planner, "plan", None)):
                _tentacle_planner = StaticPlanner()
            _tentacle_engine = CerebrumDecisionAdapter(_tentacle_planner).decide

            _tentacle_coordinator = TentacleCoordinator(
                host="0.0.0.0",  # nosec B104 — tentacle WS server, intentional LAN bind
                port=_tentacle_ws_port,
                dashboard_port=None,
                decision_engine=_tentacle_engine,
                auth_token=_tentacle_token,
            )
            app.include_router(
                create_tentacle_router(
                    _tentacle_coordinator,
                    identity_store=ctx.identity_store,
                    require_auth=ctx.require_auth,
                    jwt_secret=ctx.jwt_secret,
                    jwt_issuer=ctx.jwt_issuer,
                    jwt_audience=ctx.jwt_audience,
                )
            )
            app.include_router(
                create_tentacle_join_router(
                    ws_port=_tentacle_ws_port,
                    auth_token=_tentacle_token,
                )
            )
            app.state.tentacle_coordinator = _tentacle_coordinator
            set_active_coordinator(_tentacle_coordinator)

            async def _start_tentacle_bridge() -> None:
                try:
                    await _tentacle_coordinator.start()
                except Exception:  # noqa: BLE001
                    logging.getLogger(__name__).warning(
                        "tentacle WS server failed to start; phones can't join the team",
                        exc_info=True,
                    )

            async def _stop_tentacle_bridge() -> None:
                try:
                    await _tentacle_coordinator.stop()
                except Exception:  # noqa: BLE001
                    logging.getLogger(__name__).warning(
                        "tentacle WS server failed to stop cleanly",
                        exc_info=True,
                    )
                finally:
                    set_active_coordinator(None)

            app.router.add_event_handler("startup", _start_tentacle_bridge)
            app.router.add_event_handler("shutdown", _stop_tentacle_bridge)
        except Exception:  # noqa: BLE001
            logging.getLogger(__name__).warning(
                "tentacle bridge unavailable (missing deps?); phones can't join the team",
                exc_info=True,
            )

    # Generic semantic ranking · /api/retrieve/rank — order candidate texts by
    # meaning (configurable embedder, lexical fallback). A connected phone uses
    # it to pick the right skill/cached action instead of keyword matching.
    from runtime.sensing.gateway.retrieve_router import create_retrieve_router

    app.include_router(
        create_retrieve_router(
            identity_store=ctx.identity_store,
            require_auth=ctx.require_auth,
            jwt_secret=ctx.jwt_secret,
            jwt_issuer=ctx.jwt_issuer,
            jwt_audience=ctx.jwt_audience,
        )
    )

    # ─── Persistent terminal WebSocket ─────────
    from runtime.sensing.gateway.terminal_router import mount_terminal_routes

    mount_terminal_routes(
        app,
        identity_store=ctx.identity_store,
        require_auth=ctx.require_auth,
        jwt_secret=ctx.jwt_secret,
        jwt_issuer=ctx.jwt_issuer,
        jwt_audience=ctx.jwt_audience,
    )

    # ─── IM Channels webhook / dashboard APIs ─────────
    # sessions where the full stack-backed ChannelManager was not created.
    # In that case a small local manager lets the router expose the supported
    # platform list and credential state instead of returning 404.
    from runtime.sensing.gateway.channels_router import create_channels_router

    app.include_router(
        create_channels_router(
            manager=channel_manager,
            identity_store=ctx.identity_store,
            require_auth=ctx.require_auth,
            jwt_secret=ctx.jwt_secret,
            jwt_issuer=ctx.jwt_issuer,
            jwt_audience=ctx.jwt_audience,
        )
    )
