# Echo OS on-demand eSCL/WSD scanner policy.

[devices]

[options]
discovery = enable
model = network
protocol = auto
ws-discovery = fast
pretend-local = false

[debug]
enable = false
hexdump = false

[blacklist]
