import {
  AudioLinesIcon,
  BoxIcon,
  ClapperboardIcon,
  CuboidIcon,
  FileTextIcon,
  ImageIcon,
  PanelsTopLeftIcon,
  SparklesIcon,
  Table2Icon,
  VideoIcon,
  WorkflowIcon,
  type LucideIcon,
} from "lucide-react";

import type { DesignNodeKind } from "./canvas-model";

export type DesignSection = "home" | "canvas" | "assets" | "skills" | "comfyui";
export type WorkspaceLayout = "split" | "chat-left" | "chat" | "canvas";

export type NativeNodeTemplate = {
  kind: DesignNodeKind;
  title: string;
  description: string;
  icon: LucideIcon;
  badge?: string;
};

export const NATIVE_NODE_TEMPLATES: NativeNodeTemplate[] = [
  {
    kind: "text",
    title: "文本",
    description: "剧本、广告词、品牌文案",
    icon: FileTextIcon,
  },
  {
    kind: "table",
    title: "表格",
    description: "结构化的行列数据",
    icon: Table2Icon,
  },
  {
    kind: "image",
    title: "图片",
    description: "海报、分镜、角色设计",
    icon: ImageIcon,
  },
  {
    kind: "video",
    title: "视频",
    description: "创意广告、动画与电影镜头",
    icon: VideoIcon,
  },
  {
    kind: "audio",
    title: "音频",
    description: "音效、配音与音乐",
    icon: AudioLinesIcon,
  },
  {
    kind: "director",
    title: "3D 导演台",
    description: "角色、机位与运镜编排",
    icon: CuboidIcon,
    badge: "新",
  },
  {
    kind: "editor",
    title: "视频剪辑",
    description: "多轨时间线剪辑，全屏打开编辑",
    icon: ClapperboardIcon,
    badge: "新",
  },
  {
    kind: "comfyui",
    title: "ComfyUI 工作流",
    description: "节点式 AI 绘图工作流，全屏打开编辑",
    icon: WorkflowIcon,
    badge: "新",
  },
  {
    kind: "output",
    title: "交付物",
    description: "汇总画布结果并写入项目",
    icon: BoxIcon,
  },
];

export const CREATIVE_SKILL_COLLECTION = [
  {
    id: "creative-anime-pv",
    title: "动画游戏 PV",
    category: "动画",
    description: "从世界观和角色卖点生成镜头、音乐与节奏一致的 PV 方案。",
    icon: SparklesIcon,
    tone: "from-violet-500/35 via-fuchsia-400/18 to-indigo-500/10",
    downloads: "3.4k",
  },
  {
    id: "creative-brand-film",
    title: "品牌宣传短片",
    category: "商业广告",
    description: "把品牌策略转为视觉锚点、镜头系统与多渠道成片。",
    icon: PanelsTopLeftIcon,
    tone: "from-sky-500/35 via-cyan-400/18 to-blue-500/10",
    downloads: "5.6k",
  },
  {
    id: "creative-title-sequence",
    title: "电影片头设计",
    category: "专业影视",
    description: "围绕叙事主题编排字体、转场、演职员表与视效节奏。",
    icon: ClapperboardIcon,
    tone: "from-zinc-700/50 via-slate-500/20 to-orange-400/10",
    downloads: "2.5k",
  },
  {
    id: "creative-music-video",
    title: "音乐 MV 导演",
    category: "音频音乐",
    description: "从歌曲结构建立表演、空间、剪辑和动态字幕方案。",
    icon: AudioLinesIcon,
    tone: "from-pink-500/35 via-rose-400/18 to-purple-500/10",
    downloads: "4.5k",
  },
  {
    id: "creative-education-video",
    title: "教育可视化工作室",
    category: "教育",
    description: "把知识目标拆为讲解、图解、练习和理解验证。",
    icon: Table2Icon,
    tone: "from-emerald-500/35 via-lime-400/16 to-teal-500/10",
    downloads: "2.8k",
  },
  {
    id: "creative-visual-direction",
    title: "视觉风格导演",
    category: "创意实验",
    description: "统一构图、材质、色彩、字体与动态语言。",
    icon: ImageIcon,
    tone: "from-amber-500/35 via-orange-400/18 to-red-500/10",
    downloads: "4.2k",
  },
  {
    id: "creative-koc-video",
    title: "KOC 口播短片",
    category: "电商",
    description: "完成开场钩子、口播脚本、镜头清单与素材路由。",
    icon: VideoIcon,
    tone: "from-orange-500/35 via-yellow-400/18 to-pink-500/10",
    downloads: "2.7k",
  },
  {
    id: "creative-ui-motion",
    title: "UI 动效广告",
    category: "商业广告",
    description: "将产品界面转成品牌一致的动效分镜与制作规范。",
    icon: PanelsTopLeftIcon,
    tone: "from-blue-500/35 via-violet-400/18 to-fuchsia-500/10",
    downloads: "1.7k",
  },
  {
    id: "creative-video-deconstruct",
    title: "视频逆向拆解",
    category: "平台工具",
    description: "从参考视频提取镜头、节奏、视觉技术与可复用提示结构。",
    icon: WorkflowIcon,
    tone: "from-cyan-500/35 via-slate-400/18 to-indigo-500/10",
    downloads: "3.4k",
  },
  {
    id: "creative-3d-animation",
    title: "3D 动画短片",
    category: "动画",
    description: "完成角色场景设定、镜头规划、动作预演与视频合成。",
    icon: CuboidIcon,
    tone: "from-blue-400/45 via-violet-400/22 to-pink-400/10",
    downloads: "7.5k",
  },
  {
    id: "creative-product-ad",
    title: "极简产品广告",
    category: "商业广告",
    description: "从产品素材提炼单一卖点，生成可信的极简广告短片。",
    icon: BoxIcon,
    tone: "from-yellow-300/50 via-amber-200/25 to-zinc-100/20",
    downloads: "5.0k",
  },
  {
    id: "creative-paper-collage",
    title: "纸拼贴讲解动画",
    category: "教育",
    description: "把文案和知识节点转成分层纸艺、手作运动与触感声音。",
    icon: PanelsTopLeftIcon,
    tone: "from-red-500/40 via-orange-300/18 to-amber-100/15",
    downloads: "4.1k",
  },
  {
    id: "creative-character-performance",
    title: "人物微表情视频",
    category: "专业影视",
    description: "按角色动机设计视线、呼吸、微表情与肢体表演。",
    icon: VideoIcon,
    tone: "from-stone-500/42 via-rose-300/18 to-sky-200/12",
    downloads: "3.2k",
  },
  {
    id: "creative-fpv-video",
    title: "第一视角 FPV 穿越",
    category: "创意实验",
    description: "按空间拓扑规划连续路线、速度曲线与一镜到底穿越。",
    icon: VideoIcon,
    tone: "from-sky-400/45 via-indigo-400/18 to-zinc-800/16",
    downloads: "2.9k",
  },
  {
    id: "creative-localization-dubbing",
    title: "多语言出海配音",
    category: "音频音乐",
    description: "保持角色音色、语气、时长、口型与字幕同步的本地化。",
    icon: AudioLinesIcon,
    tone: "from-emerald-400/40 via-cyan-300/18 to-blue-400/12",
    downloads: "2.4k",
  },
  {
    id: "creative-broll-planner",
    title: "口播 B-roll 规划",
    category: "平台工具",
    description: "把逐字稿拆成可审片的镜头、素材来源和覆盖关系。",
    icon: ClapperboardIcon,
    tone: "from-slate-500/42 via-cyan-300/18 to-amber-300/12",
    downloads: "2.2k",
  },
  {
    id: "creative-dynamic-poster",
    title: "动态海报生成",
    category: "商业广告",
    description: "保持文字和版式清晰，将静态海报扩展为可循环动态视觉。",
    icon: ImageIcon,
    tone: "from-fuchsia-500/42 via-pink-300/20 to-orange-200/10",
    downloads: "1.5k",
  },
  {
    id: "creative-h3-prompt-director",
    title: "多模态视频提示词导演",
    category: "平台工具",
    description: "把零散需求和参考素材整理成可控、可执行的视频模型指令。",
    icon: WorkflowIcon,
    tone: "from-violet-600/45 via-blue-400/20 to-zinc-900/12",
    downloads: "2.4k",
  },
  {
    id: "creative-vox-explainer",
    title: "拼贴科普短片",
    category: "教育",
    description: "把文章或报告转成旁白、字幕、图解与拼贴节奏统一的短片。",
    icon: PanelsTopLeftIcon,
    tone: "from-amber-500/42 via-red-300/18 to-slate-700/12",
    downloads: "2.3k",
  },
  {
    id: "creative-lip-makeup-ad",
    title: "唇部彩妆广告",
    category: "商业广告",
    description: "设计自然可信的唇部特写、上妆动作和产品定帧。",
    icon: VideoIcon,
    tone: "from-rose-600/48 via-pink-300/20 to-red-950/14",
    downloads: "2.2k",
  },
  {
    id: "creative-silkscreen-film",
    title: "丝印装饰插画短片",
    category: "创意实验",
    description: "用有限色版、颗粒套印和同步声音构建装饰插画短片。",
    icon: ImageIcon,
    tone: "from-indigo-700/45 via-orange-400/22 to-yellow-200/14",
    downloads: "2.1k",
  },
  {
    id: "creative-line-explainer",
    title: "线条图解科普视频",
    category: "教育",
    description: "用线条角色、图标和关系图解释抽象知识与因果过程。",
    icon: Table2Icon,
    tone: "from-zinc-800/46 via-sky-300/20 to-white/10",
    downloads: "1.9k",
  },
  {
    id: "creative-dodge-game-video",
    title: "躲避游戏反应视频",
    category: "动画",
    description: "从角色参考生成四向动作、障碍反馈和短时反应挑战。",
    icon: VideoIcon,
    tone: "from-emerald-600/45 via-lime-300/20 to-slate-900/14",
    downloads: "1.9k",
  },
  {
    id: "creative-dotmatrix-brand-motion",
    title: "点阵品牌字形动效",
    category: "UI 动效",
    description: "建立可读的点阵字形、品牌锁定和扫描聚合动效。",
    icon: SparklesIcon,
    tone: "from-black/55 via-violet-500/30 to-cyan-300/16",
    downloads: "1.7k",
  },
  {
    id: "creative-digital-product-film",
    title: "数字产品宣传片",
    category: "商业广告",
    description: "把真实界面与交互路径转成准确、电影感的产品演示。",
    icon: PanelsTopLeftIcon,
    tone: "from-slate-950/55 via-cyan-600/25 to-emerald-300/14",
    downloads: "1.7k",
  },
  {
    id: "creative-brand-flow-mg",
    title: "品牌流线 MG 动效",
    category: "UI 动效",
    description: "从品牌标志提取流线、节点和收束规则，形成统一 MG 动效。",
    icon: WorkflowIcon,
    tone: "from-blue-700/45 via-fuchsia-400/22 to-amber-200/12",
    downloads: "1.3k",
  },
  {
    id: "creative-liveaction-drawing-reveal",
    title: "实景动态手绘显影",
    category: "创意实验",
    description: "跟踪真实运动，由笔尖将主体逐层显影为手绘视觉。",
    icon: ImageIcon,
    tone: "from-stone-700/45 via-sky-300/18 to-orange-200/12",
    downloads: "1.3k",
  },
  {
    id: "creative-toy-grid-poster",
    title: "IP 潮玩六宫格动态海报",
    category: "电商",
    description: "保持角色身份一致，制作六姿态潮玩格与竖版动态海报。",
    icon: CuboidIcon,
    tone: "from-purple-600/45 via-pink-300/20 to-sky-300/14",
    downloads: "1.2k",
  },
  {
    id: "creative-director-stage",
    title: "3D 导演台编排",
    category: "平台工具",
    description: "编排角色、场景、相机、动作 DSL、运镜路径和可撤销时间线。",
    icon: CuboidIcon,
    tone: "from-lime-400/40 via-emerald-300/18 to-slate-700/12",
    downloads: "内置",
  },
  {
    id: "creative-video-editor",
    title: "多轨视频剪辑",
    category: "平台工具",
    description: "组织媒体、字幕、对白、音乐、转场和版本导出。",
    icon: ClapperboardIcon,
    tone: "from-rose-500/42 via-purple-300/18 to-zinc-800/12",
    downloads: "内置",
  },
  {
    id: "creative-comfyui-workflow",
    title: "ComfyUI 工作流编排",
    category: "平台工具",
    description: "诊断本机节点和模型，安全编辑、排队并验收真实工作流结果。",
    icon: WorkflowIcon,
    tone: "from-sky-500/42 via-cyan-300/18 to-indigo-700/14",
    downloads: "内置",
  },
  {
    id: "creative-promo-video",
    title: "宣传视频",
    category: "商业广告",
    description: "把产品简介转成有事实证据、镜头节奏和渠道版本的宣传片。",
    icon: VideoIcon,
    tone: "from-indigo-600/45 via-sky-300/20 to-white/10",
    downloads: "11.4k",
  },
  {
    id: "creative-ecommerce-images",
    title: "电商商品图",
    category: "电商",
    description: "从真实商品素材生成主图、卖点、场景、细节和规格图组。",
    icon: ImageIcon,
    tone: "from-orange-400/45 via-amber-200/22 to-white/15",
    downloads: "22.2k",
  },
  {
    id: "creative-audiobook",
    title: "有声书制作",
    category: "音频音乐",
    description: "完成书稿清理、多角色选角、表演、环境声和章节交付。",
    icon: AudioLinesIcon,
    tone: "from-amber-800/45 via-orange-300/18 to-stone-100/12",
    downloads: "20.3k",
  },
  {
    id: "creative-storyboard-assets",
    title: "角色场景分镜资产",
    category: "专业影视",
    description: "把角色、场景、道具与镜头统一为可连续生产的设定板。",
    icon: ClapperboardIcon,
    tone: "from-slate-700/45 via-cyan-300/18 to-amber-200/12",
    downloads: "10.9k",
  },
  {
    id: "creative-sleep-audio",
    title: "助眠音频",
    category: "音频音乐",
    description: "设计低刺激的冥想旁白、环境层、循环点与响度曲线。",
    icon: AudioLinesIcon,
    tone: "from-indigo-900/50 via-blue-400/22 to-violet-200/12",
    downloads: "2.4k",
  },
  {
    id: "creative-beat-sync-edit",
    title: "音乐卡点剪辑",
    category: "音频音乐",
    description: "按音乐结构、动作与语义变化设计卡点、变速和声音衔接。",
    icon: ClapperboardIcon,
    tone: "from-fuchsia-600/45 via-rose-300/20 to-cyan-300/12",
    downloads: "3.7k",
  },
  {
    id: "creative-editor-export",
    title: "剪辑工程导出",
    category: "平台工具",
    description: "整理媒体、字幕、代理和兼容性，输出可迁移剪辑工程包。",
    icon: BoxIcon,
    tone: "from-zinc-800/50 via-slate-400/20 to-blue-200/10",
    downloads: "21.4k",
  },
  {
    id: "creative-documentary",
    title: "纪录片制作",
    category: "专业影视",
    description: "把研究、采访和素材组织成事实可追溯的纪录片结构。",
    icon: VideoIcon,
    tone: "from-stone-700/48 via-amber-400/18 to-sky-200/12",
    downloads: "3.4k",
  },
  {
    id: "creative-film-score",
    title: "影视配乐",
    category: "音频音乐",
    description: "为角色与场景设计主题动机、配器、动态和音乐进出点。",
    icon: AudioLinesIcon,
    tone: "from-violet-800/48 via-rose-400/20 to-amber-200/12",
    downloads: "3.9k",
  },
  {
    id: "creative-image-remix",
    title: "图片重混",
    category: "创意实验",
    description: "提取参考图的构图、光线和材质关系，形成原创视觉变体。",
    icon: ImageIcon,
    tone: "from-emerald-700/44 via-cyan-300/20 to-fuchsia-300/14",
    downloads: "21.1k",
  },
  {
    id: "creative-pixel-block-art",
    title: "像素方块画",
    category: "创意实验",
    description: "将图像简化为可搭建网格、有限调色板与材料清单。",
    icon: CuboidIcon,
    tone: "from-emerald-500/45 via-lime-300/22 to-amber-300/14",
    downloads: "2.7k",
  },
  {
    id: "creative-voice-design",
    title: "声音设计",
    category: "音频音乐",
    description: "以表演意图和声学参数建立合规的原创音色方向。",
    icon: AudioLinesIcon,
    tone: "from-sky-700/45 via-violet-300/20 to-pink-200/12",
    downloads: "3.2k",
  },
  {
    id: "creative-anime-style-forge",
    title: "动画风格锻造",
    category: "动画",
    description: "统一角色和场景的线条、比例、上色、材质与运动规则。",
    icon: SparklesIcon,
    tone: "from-rose-600/42 via-violet-300/22 to-sky-300/12",
    downloads: "2.8k",
  },
  {
    id: "creative-cinematic-shot-cards",
    title: "影视镜头与角色卡",
    category: "专业影视",
    description: "明确机位、焦段、调度、光线、表演和连续性约束。",
    icon: ClapperboardIcon,
    tone: "from-zinc-900/52 via-blue-500/20 to-orange-300/12",
    downloads: "6.7k",
  },
  {
    id: "creative-image-inpaint",
    title: "图片局部重绘",
    category: "平台工具",
    description: "按遮罩修改目标区域并保持透视、光线与外部内容稳定。",
    icon: ImageIcon,
    tone: "from-cyan-600/42 via-sky-300/20 to-white/14",
    downloads: "3.1k",
  },
  {
    id: "creative-multi-angle-render",
    title: "多角度渲染",
    category: "平台工具",
    description: "固定主体结构与身份锚点，生成多方位相机视角。",
    icon: CuboidIcon,
    tone: "from-slate-600/44 via-teal-300/20 to-amber-200/12",
    downloads: "3.1k",
  },
  {
    id: "creative-multiboard",
    title: "多宫格分镜",
    category: "专业影视",
    description: "将故事拆成顺序清晰、空间连续、角色一致的分镜整图。",
    icon: PanelsTopLeftIcon,
    tone: "from-amber-600/44 via-orange-300/20 to-sky-300/12",
    downloads: "4.3k",
  },
  {
    id: "creative-lighting-studio",
    title: "光影工作室",
    category: "专业影视",
    description: "设计有动机的光线方向、软硬、色温、光比和空间层次。",
    icon: SparklesIcon,
    tone: "from-yellow-300/50 via-orange-200/24 to-zinc-900/18",
    downloads: "2.8k",
  },
  {
    id: "creative-microdrama-writer",
    title: "微短剧剧集编剧",
    category: "短剧漫剧",
    description: "规划钩子、持续冲突、人物选择、集尾悬念与制作复用。",
    icon: FileTextIcon,
    tone: "from-red-700/45 via-rose-300/20 to-slate-800/14",
    downloads: "4.6k",
  },
  {
    id: "creative-podcast-kit",
    title: "播客内容套件",
    category: "平台工具",
    description: "从播客生成章节、说明、短切片、长文和社媒内容包。",
    icon: AudioLinesIcon,
    tone: "from-purple-700/45 via-orange-300/18 to-pink-200/12",
    downloads: "2.4k",
  },
  {
    id: "creative-dual-player-intro",
    title: "双人游戏开场",
    category: "动画",
    description: "从两位玩家角色参考生成身份稳定、菜单清楚的游戏开场动画。",
    icon: VideoIcon,
    tone: "from-cyan-500/40 via-violet-400/20 to-slate-900/14",
    downloads: "2.7k",
  },
  {
    id: "creative-paper-stopmotion-explainer",
    title: "纸艺定格科普",
    category: "教育",
    description: "用纸偶、分层布景和逐帧动作讲清可验证的知识链路。",
    icon: ClapperboardIcon,
    tone: "from-amber-500/42 via-rose-300/18 to-stone-500/12",
    downloads: "2.8k",
  },
  {
    id: "creative-course-landing-page",
    title: "技能课程详情页",
    category: "教育",
    description: "把课程成果、模块和证据组织成可实现、可转化的详情页。",
    icon: PanelsTopLeftIcon,
    tone: "from-blue-500/36 via-indigo-300/18 to-white/10",
    downloads: "2.2k",
  },
  {
    id: "creative-zodiac-english-series",
    title: "文化角色英语启蒙",
    category: "教育",
    description: "规划儿童英语故事、儿歌、重复句型和连续剧集资产。",
    icon: AudioLinesIcon,
    tone: "from-red-500/36 via-yellow-300/22 to-emerald-400/12",
    downloads: "1.6k",
  },
  {
    id: "creative-dreamcore-space",
    title: "梦核阈限空间",
    category: "创意实验",
    description: "建立自洽的异常空间规则、镜头漫游和环境声音氛围。",
    icon: CuboidIcon,
    tone: "from-lime-300/35 via-cyan-200/18 to-violet-800/18",
    downloads: "1.6k",
  },
  {
    id: "creative-cinematic-style-extractor",
    title: "电影风格规则提炼",
    category: "专业影视",
    description: "从参考影像提炼构图、镜头、光色和声音规则并原创迁移。",
    icon: ClapperboardIcon,
    tone: "from-zinc-900/52 via-amber-300/18 to-cyan-300/10",
    downloads: "1.5k",
  },
  {
    id: "creative-intentional-lowpoly-film",
    title: "有意低模影像",
    category: "创意实验",
    description: "用可控的低面数、笨拙绑定和生硬运镜建立一致失败感。",
    icon: BoxIcon,
    tone: "from-fuchsia-500/34 via-blue-400/20 to-lime-300/12",
    downloads: "1.3k",
  },
] as const;

export const COMFY_WORKFLOWS = [
  {
    id: "text-to-image",
    title: "基础文生图",
    description: "提示词、采样、VAE 解码与图片保存的核心节点工作流。",
    tags: ["基础", "核心节点"],
    availability: "bundled",
  },
  {
    id: "image-remix",
    title: "参考图重绘",
    description: "编码参考图并以可调重绘强度生成构图一致的视觉变体。",
    tags: ["图生图", "核心节点"],
    availability: "bundled",
  },
  {
    id: "latent-upscale",
    title: "潜空间高清放大",
    description: "潜空间二倍放大与低强度重采样，兼顾细节和一致性。",
    tags: ["高清", "2×"],
    availability: "bundled",
  },
  {
    id: "storyboard-consistency",
    title: "角色一致性分镜",
    description: "用参考图和结构控制在多个镜头间保持角色、服装与场景。",
    tags: ["分镜", "需扩展"],
    availability: "dependency",
  },
  {
    id: "image-to-video",
    title: "首帧图片转视频",
    description: "把关键帧、运动提示和视频模型连接成可复用镜头工作流。",
    tags: ["视频", "需模型"],
    availability: "dependency",
  },
  {
    id: "first-last-frame",
    title: "首尾帧镜头控制",
    description: "以开始和结束画面约束运动轨迹与镜头落点。",
    tags: ["视频", "首尾帧"],
    availability: "dependency",
  },
  {
    id: "multi-reference",
    title: "多参考一致性生成",
    description: "同时使用人物、风格、动作与场景参考控制生成结果。",
    tags: ["多参考", "一致性"],
    availability: "dependency",
  },
  {
    id: "product-background",
    title: "产品背景生成",
    description: "锁定产品外观和包装文字，批量生成电商与广告背景。",
    tags: ["电商", "蒙版"],
    availability: "dependency",
  },
  {
    id: "poster-motion",
    title: "海报动态化",
    description: "拆分海报层级并生成文字清晰、主体稳定的动态视觉。",
    tags: ["海报", "视频"],
    availability: "dependency",
  },
  {
    id: "lora-style",
    title: "LoRA 风格工作流",
    description: "挂载本机 LoRA，以指定人物或视觉风格生成一致内容。",
    tags: ["LoRA", "需模型"],
    availability: "dependency",
  },
] as const;
